### ISSUE TITLE
Galaxy tab s7 plus android 12 Spen  is not well recognize this last update 

### ISSUE THREAD

**Issue by montana013** [moonlight-stream/moonlight-android#1030]
I have been using the Samsung s7+ stylus for a year without any problem with moonlight but for 2 days the application has been unable to recognize the stylus and reacts haphazardly. When I use my finger as a stylus it works but it is much slower  au with the Spen..
My spen work well in other android ap.
Thx

**Comment by RunawayFixer** [comment]
I'm in the same situation with my Samsung s7+. I updated moonlight today and the spen stops working properly as soon as I connect to the PC. It was still working properly saturday a week ago. Even the android functions (moving spen up from bottom of the screen) no longer work once moonlight is connected to a pc. In the windows desktop the spen is all over the place. Moving the spen to the right moves the mouse cursor to the left. Using fingers still works, both for opening the android functions and for touch control.

**Comment by montana013** [comment]
I Think's its an android 12  issue not moonlight problèm uptdate Because when i install old version i have same issue

**Comment by RunawayFixer** [comment]
Yeah, the issue seems to be on the android side, indicated by the spen no longer able to control android functions while moonlight is active. But it's still only the moonlightstreamer that is having issues.

I've restarted my tablet to safe mode, uninstalled the moonlightstreamer app, restarted the tablet, reinstalled the app. Connected to the pc again. My spen is still screwed up, too sensitive and now moving the spen to the left moves the mouse cursor up, spen up moves cursor to the right and so on.

Downgrading android is a step too far for me, I'll just have to hope for an eventual fix.

**Comment by chancemon** [comment]
This is fixed in #1039

**Comment by montana013** [comment]
How can update moonlight with this fix i dont understand

**Comment by cgutman** [comment]
Fixed a while ago by 4b2e26050e2b7eedc9bca19e27709c2d62db8228 and 8a63b614955a726fc27c89bcf3699022214756d7
