### ISSUE TITLE
Auto switch HDR on/off

### ISSUE THREAD

**Issue by felipejfc** [moonlight-stream/moonlight-android#1050]
@cgutman any reason not to make HDR switching automatic (and game-independent) just as you did recently in moonlight-ios in [this](https://github.com/moonlight-stream/moonlight-ios/commit/3a77bf3e6557874aafc1f9d9774bd1f94e39cede) commit?

**Comment by cgutman** [comment]
I thought it already did last time I tried it (which was admittedly a while ago). MediaCodec seems to tunnel the HDR metadata through to the output surface format from the HEVC bitstream.

There's not a similar API to request an HDR mode change as far as I know. While there are APIs to enumerate display modes and request one, [those APIs](https://developer.android.com/reference/android/view/Display.Mode) don't expose any information about compatible colorspaces.

**Comment by felipejfc** [comment]
Sorry! You're right, it does auto switch HDR on/off. However there's a caveat, if HDR was already on when I start to stream "Desktop app" then the shield  does not turn HDR on, I need to go to Display Settings in windows and turn it off/on again. The same happens with moonlight-ios.

**Comment by cgutman** [comment]
No, that’s a bug on Nvidia’s code. If you open your NvStreamer log on the host, you’ll see that it sent HDR state 0 (off) and it’s using Rec 601/709 rather than Rec 2020.

Even if we could force the client display into HDR and lie to the decoder to avoid getting tonemapped from SDR to HDR, the extra color data is already gone from being clamped to Rec 601/709.
