### ISSUE TITLE
Controller Mapping for Mouse Emulation toggle

### ISSUE THREAD

**Issue by Jordan-Ch** [moonlight-stream/moonlight-android#1087]
Hello,

Is there a way to remap the Mouse Emulation feature to a button other than start? I use a DS4 controller and would love to be able to map this feature to the DS4 touchpad button. Some games ask you to hold the start button for some functions, which conflicts with the mouse emulation toggle. 

In the same vain, is there a way to disable the "playstation button" om DS4 from acting as a "home" input on androidTV while in the moonlight app? I would love to be able to launch the steam overlay while using moonlight. 

Thanks!

**Comment by cgutman** [comment]
> Is there a way to remap the Mouse Emulation feature to a button other than start? I use a DS4 controller and would love to be able to map this feature to the DS4 touchpad button. Some games ask you to hold the start button for some functions, which conflicts with the mouse emulation toggle.

Not currently. Out of curiosity, what Android device are you using with your DS4 controller? Recent ones should actually be able to use the DS4 touchpad for mouse control, negating the need for mouse emulation at all.

 > In the same vain, is there a way to disable the "playstation button" om DS4 from acting as a "home" input on androidTV while in the moonlight app? I would love to be able to launch the steam overlay while using moonlight.

I wish, but it depends on how the device is mapped in the OS. If it was mapped as `BUTTON_MODE`, then Moonlight will pick it up and translate that to the Mode/PS/Guide button that launches the Steam overlay. Some devices map it as a home button, which Android prevents from being intercepted by normal apps (otherwise they could prevent you from closing them).
