### ISSUE TITLE
Shield TV remote desktop mouse mode missing

### ISSUE THREAD

**Issue by lynx31** [moonlight-stream/moonlight-android#1136]
Hi, the option to enable remote desktop mouse mode is unavailable in the app version for Android TV (I am running a Shield). Any way to enable this option? Thanks

**Comment by cgutman** [comment]
This is expected behavior on Shield devices. The option is not required because Nvidia provides a better mechanism for getting the mouse behavior we want.

Shield devices support raw mouse input, so we can achieve the benefits of the remote desktop mouse mode (disabling client-side mouse acceleration) without the drawbacks (breaking compatibility with games that need to lock the cursor).

**Comment by lynx31** [comment]
Appreciate the quick reply. I was looking for this option because I seemed to have mouse lag in Moonlight on the Shield, but this has been fixed after making sure that all sessions of Parsec are closed.
