### ISSUE TITLE
Better performance with 'show performance stats while streaming'?

### ISSUE THREAD

**Issue by Lorenzoo78** [moonlight-stream/moonlight-android#1151]
I have the weirdest behaviour on a chromecast google tv 4k.

Basically, performance is abysmal (looks like 1 frame out of 5 is served).

But when enabling 'show performance stats while streaming" suddenly the chromecast is able to render a perfectly smooth stream at 80 fps with 0 frames lost.

I am at a loss here! (10.10 downloaded off the playstore)

**Comment by cgutman** [comment]
That's quite strange. What frame pacing mode are you using?

**Comment by Lorenzoo78** [comment]
I tried everything from best latency to smoothest, to no avail.

**Comment by cgutman** [comment]
Is your device running Android 10 or Android 12? What resolution and frame rate are you testing with?

**Comment by Lorenzoo78** [comment]
Android tv os version 12. 

Resolution does not impact the problem (tested 480, 720, 1080p and the bug is the same.)

Frame rate 60.

No matter the settings, performance is bad when I don't use the 'show performance the performance stats while streaming' overlay, and I get 80 frames at 1080p 60 fps when I use it.

**Comment by hunterzero99** [comment]
This seems to be the same issue I posted about in [another bug thread](https://github.com/moonlight-stream/moonlight-android/issues/1108#issuecomment-1336180387).  The refresh rate is being set to 24 or 23.97 fps for some reason.  I just tested and the show performance stats while streaming also works around this issue.

Turning off the refresh rate switching option in the ccwGTV system menu is another work around for now, but you'll have to turn it back on if you want that feature in other apps (I use it daily myself).

**Comment by Lorenzoo78** [comment]
That is exactly the issue. Turned off the refresh rate switching option, problem solved. 

I guess moonlight forces different refresh rates when the performance overlay is on or off. I guess this could be fixed in future versions hopefully?

Thank you for your answers anyways!

**Comment by cgutman** [comment]
> I guess moonlight forces different refresh rates when the performance overlay is on or off. I guess this could be fixed in future versions hopefully?

We don't actually. We always call `setFrameRate()` with the frame rate specified in the stream preferences. https://github.com/moonlight-stream/moonlight-android/blob/aa41bf8d974940bcbec258d5f6db99deadb3dc0f/app/src/main/java/com/limelight/Game.java#L2084

The OS itself is deciding the ultimate refresh rate to use. It is designed to negotiate the competing requested frame rates to determine the optimal display refresh rate to use. For example, if there are surfaces on screen displaying 24 FPS and 60 FPS content, the display will try to use 120 Hz which can accommodate both without judder.

Something seems to be going horribly wrong with the display refresh rate selection in our case. I suspect it may have to do with us using both `preferredDisplayModeId` and `setFrameRate()`.

**Comment by udllpn** [comment]
I would like to reopen this issue: I am having the exact same problem with ChromeCast with GoogleTV (Android 12). When showing stats, framerate stays at 60, and there are no discrepancies with framerate rendering.

When disabling stats, performance decreases (not hugely, but a couple of frames at least). This has been replicated in multiple ocassions.

I have tried switching the refresh rate switching option in the ccwGTV and there is no difference. 

Any help or way this can be solved. Again, with the stats present, the streams works flawlesslly. One alternative would be to include some sort of shortcut for the stats in Android in order to hide them without connecting again in order to explore if the problem persists.

**Comment by udllpn** [comment]
@cgutman 
> > The OS itself is deciding the ultimate refresh rate to use. It is designed to negotiate the competing requested frame rates to determine the optimal display refresh rate to use. For example, if there are surfaces on screen displaying 24 FPS and 60 FPS content, the display will try to use 120 Hz which can accommodate both without judder.
> 
> Something seems to be going horribly wrong with the display refresh rate selection in our case. I suspect it may have to do with us using both `preferredDisplayModeId` and `setFrameRate()`.


I would like to reopen this issue if possible: I am having the exact same problem with ChromeCast with GoogleTV (Android 12). When showing stats, framerate stays at 60, and there are no discrepancies with framerate rendering.

When disabling stats, performance decreases (not hugely, but a couple of frames at least). This has been replicated in multiple ocassions.

I have tried switching the refresh rate switching option in the ccwGTV and there is no difference.

Any help or way this can be solved. Again, with the stats present, the streams works flawlesslly. One alternative would be to include some sort of shortcut for the stats in Android in order to hide them without connecting again in order to explore if the problem persists.

**Comment by kentyman23** [comment]
It looks like this was [fixed in December](https://github.com/moonlight-stream/moonlight-android/commit/970423f873659c6db568aeda97af6a160f9c0136), but there hasn't been a release [since November](https://github.com/moonlight-stream/moonlight-android/releases). I think you need to wait for a new release to get the fix.

**Comment by cdyck** [comment]
> It looks like this was [fixed in December](https://github.com/moonlight-stream/moonlight-android/commit/970423f873659c6db568aeda97af6a160f9c0136), but there hasn't been a release [since November](https://github.com/moonlight-stream/moonlight-android/releases). I think you need to wait for a new release to get the fix.

That commit is from Dec **2022**, so it should already be in the latest release.

I'm also experiencing this issue on Chromecast with Google TV 4K on Android 12. Tried seemingly every combination of frame pacing, refresh rate switching, as well as the "Disable HW Overlays" fix described [here](https://www.reddit.com/r/Chromecast/comments/18sbrfz/chromecast_4k_3rd_gen_video_stuttering_smoothness/), but the only way I am able to get a smooth stream is by enabling the performance stats overlay in Moonlight.

**Comment by kentyman23** [comment]
Ohp, good eye, I missed the year.

**Comment by cdyck** [comment]
Looks like maybe there is a [Chromecast update rolling out with a fix for stuttering](https://www.googlenestcommunity.com/t5/Chromecast/Frame-drops-google-tv-4K/td-p/573147), so maybe this will be fixed by that 🤞

**Comment by udllpn** [comment]
To be honest, it's quite uncanny. I have been trying all sort of settings, and this only happens using "balanced" frame pacing (so other settings perform worse). 

Maybe a practical option would be to allow stats to be on but "hidden" to see if this solves the issue.

**Comment by agustinmorantes** [comment]
Hello, is there any update on this? It's still happening to me, and the stuttering is bad enough that I cannot use my chromecast to stream with moonlight. The recent firmware updates did not fix this. 
If there's anything I can do on my end to help identify the cause of the issue I'm happy to help.

**Comment by udllpn** [comment]
Any potential updates. 

It is really unmotivating to find that everything works flawlessly when the stat box is active, but that frame pacing starts changing once the stats are deactivated. 

Thank you in advance.

**Comment by hunterzero99** [comment]
This particular issue was fixed in 2022.  If you are all legitimately experiencing it again?  Is your Moonlight app up to date?  I'm not sure what the best protocol is, but if you can't reopen this bug report, then I would recommend you file a new one.

Back in 2022 when I had this issue, the best work around was to manually turn of framerate switching in the Chromecast settings, and select your resolution and framerate there.

**Comment by udllpn** [comment]
Yes, I can confirm that I am using the latest version of everything. As commented above, a few months ago the issue was not present, but since November (more or less), it was very noticeable. I am using Sunshine right now, but I have tested everything. 

I am currently disabling the overlay options in the Chromecast developer options, as it always generates issues.

**Comment by udllpn** [comment]
Just a quick update: the latest version of Google Chromecast has just suddenly fixed the issue. Things have reverted to how they were a few months ago.
