### ISSUE TITLE
FireTV - Black Screen

### ISSUE THREAD

**Issue by Araxus2k** [moonlight-stream/moonlight-android#117]
Hi i would like to stream from my desktop pc (resolution:1920:1200) to my TV with my FireTV Box. Its working fine with 720p (30/60). However when i change the resolution to 1080p(30/60) the connection is established (like music/audio from my pc is playing on the TV) but the screen stays black. Im using a wired connection and the latest version of Moonlight/GForce Experience.

**Comment by darrennoble** [comment]
Do you have the older Fire TV or the newer 4k Fire TV?  I have the older non-4k Fire TV and I had to go into the settings, then select H.265 Settings, and set it to Never Use H.265.  The older Fire TVs don't have a hardware h.265 decoder and so must use H.264 instead and sometimes the autodetect has issues on my Fire TV.

Also depending on what's going on in the game (fast action / fast screen updates, complex textures, or other hard to compress video), I have to lower the settings to 720p / 30 fps because  my fire tv laggs too much and sometimes skips.  I've actually stopped using the Fire TV / moonlight for streaming to my TV (I still use it on my phone, tablet, and laptop though) because the Fire TV doesn't work great with it and with my last video card (it was an AMD) I had purchased a wireless HDMI streamer that can stream any HDMI source at 1080p 30fps to my tv (it has a dongle that plugs into the HDMI on my vidoe card and a usb port on the PC for power, and then streams wirelessly to a box just slightly larger than a Fire TV that connects to my receiver / TV).  The video quality on it is a little worse than moonlight, but not bad.  But there is little lag and for me it almost never skipps.
