### ISSUE TITLE
[Issue]: Diablo Immortal no Gamepad detected..

### ISSUE THREAD

**Issue by ruthan** [moonlight-stream/moonlight-android#1226]
### Describe the bug

Im able to make other games working fine with same setup, but Diablo immortal is not registering gamepad input, for example Diablo IV does..

### Steps to reproduce

Install Diablo Immortal, its free, add it into Steam not Steam game.. start or it.. Batllenet launcher starts.. start game through launcher.
  I know that game has Android version, but in some cases PC version is better and its valid test case..
  PS4 controller used on android..

### Affected games

Diablo Immortal..

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

Default. 

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

No

### Android version

Android 12

### Device model

Sony Xperia 10 III

### Server PC OS version

Windows 10 22H2

### Server PC GeForce Experience version

lastest

### Server PC Nvidia GPU driver version

lastest

### Server PC antivirus and firewall software

Avira

**Comment by cgutman** [comment]
This is a host-side issue (either Sunshine or GeForce Experience), not a bug in the Moonlight client. I suggest following up with the host software bug tracker.

**Comment by ruthan** [comment]
Hmm, im using Geforce Experience.. so Moonlight is just some communication layer for remote connecting? all other code is reused from third party apps? I hoped that is possible to fix it.

**Comment by cgutman** [comment]
Moonlight is the client. It handles sending input to the host and playing the audio and video. The host software is what is responsible for passing Moonlight's input data into the game and sending audio/video back to Moonlight.

Since the input works in other games, that indicates that Moonlight is sending input properly, but the host or game is not passing it through. This may be deliberate by the game to avoid possible cheats, but I'm not sure about that game in particular.
