### ISSUE TITLE
[Issue]: Triggering game vibrations during G Cloud streaming can cause 30 ms or so of network fluctuations

### ISSUE THREAD

**Issue by 137615** [moonlight-stream/moonlight-android#1250]
### Describe the bug

In your newly submitted vibrator recognition optimization feature, this change allows the G Cloud to trigger vibrations without turning on the analog vibrations. But because the network latency increases when the G Cloud vibrates, can you try to optimize this problem? Otherwise this will mean that later versions of the G Cloud will always have the problem of network fluctuations when they vibrate (unless the vibration in the game settings is turned off).

### Steps to reproduce

Game-Time Trigger Supporting Multi-Level Vibration with G Cloud Stream

### Affected games

Genshine Impact,Beyond: Two Souls

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

Resolution 1920.1080, Frame Rate 60fps, Sound and Computer Playback, H 265 Decoding

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

11

### Device model

G Cloud

### Server PC OS version

windows 11

### Server PC GeForce Experience version

Sunshine used

### Server PC Nvidia GPU driver version

537.34

### Server PC antivirus and firewall software

Huorong Internet Security

**Comment by cgutman** [comment]
I changed the rumble operations (and other callbacks) to take place on a separate thread to ensure the control stream thread is not blocked waiting for the rumble to be sent to the hardware in https://github.com/moonlight-stream/moonlight-android/commit/833ef3630b7c9e4dfd0ea86377bbcc7200786b78

I never saw rumble callbacks taking anywhere near 30 ms on my G Cloud, but try the latest code and see if it improves your experience.

This fix is the best we can do in Moonlight itself. It's still possible for rumble to cause increased network latency due to factors outside our control, such as temporary RF interference caused by activating the vibrators or latency introduced on Sunshine's end when sending rumble events.

**Comment by 137615** [comment]
> 我将隆隆声操作（和其他回调）更改为在单独的线程上进行，以确保控制流线程不会被阻塞，等待隆隆声发送到 [833ef36](https://github.com/moonlight-stream/moonlight-android/commit/833ef3630b7c9e4dfd0ea86377bbcc7200786b78) 中的硬件
> 
> 我从未在我的 G Cloud 上看到过接近 30 毫秒的隆隆回调，但请尝试最新的代码，看看它是否能改善您的体验。
> 
> 此修复是我们在月光本身中可以做的最好的。由于我们无法控制的因素，隆隆声仍有可能导致网络延迟增加，例如激活振动器引起的临时射频干扰或发送隆隆声事件时在 Sunshine 端引入的延迟。

Great, this method works, this problem has been fixed, thank you very much

> I changed the rumble operations (and other callbacks) to take place on a separate thread to ensure the control stream thread is not blocked waiting for the rumble to be sent to the hardware in [833ef36](https://github.com/moonlight-stream/moonlight-android/commit/833ef3630b7c9e4dfd0ea86377bbcc7200786b78)
> 
> I never saw rumble callbacks taking anywhere near 30 ms on my G Cloud, but try the latest code and see if it improves your experience.
> 
> This fix is the best we can do in Moonlight itself. It's still possible for rumble to cause increased network latency due to factors outside our control, such as temporary RF interference caused by activating the vibrators or latency introduced on Sunshine's end when sending rumble events.

Great, this method works, this problem has been fixed, thank you very much！
