### ISSUE TITLE
[Issue]: Galaxy note 20 ultra stylus not functioning exclusively in civilization 6.

### ISSUE THREAD

**Issue by littlejonn3490** [moonlight-stream/moonlight-android#1317]
### Describe the bug

Stylus works as intended on desktop itself and all other applications, in civilization 6 it allows me to move my cursor but not click.

### Steps to reproduce

Connect to sunshine host on PC with a galaxy note 20 ultra (or presumably any note series with a stylus), and attempt to click on anything using the stylus.

### Affected games

Civilization VI

### Other Moonlight clients

Untested, stylus only works on android

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

I've increased my bit rate and attempted to use the stylus with trackpad mode on and off.

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

Android 12

### Device model

Samsung galaxy note 20 ultra 5g

### Server PC OS version

Windows 10 pro 19045

### Server PC Sunshine version

0.21.0

### Server PC Nvidia GPU driver version

546.65

### Server PC antivirus and firewall software

Windows defender

### Screenshots

https://imgur.com/a/COz3LPm

### Additional context

I am worried that this will get written off as a non-issue, so here's some context. The stylus allows me to freely move my cursor without actually touching the screen which makes it much more precise. I can hover over small elements on the screen without my finger being in the way or worrying about an unwanted hold and drag happening when repositioning my cursor

**Comment by cgutman** [comment]
This isn't a Moonlight bug, since the pen events are making to the host successfully. It's a Sunshine app compatibility issue, so that should go on the Sunshine bug tracker instead.

However, I think there is already a workaround for this in Sunshine nightly builds - https://github.com/LizardByte/Sunshine/releases/nightly-dev

On the Input tab, change "Native Pen/Touch Support" to disabled and see if that fixes it. If not, please file a bug on Sunshine.
