### ISSUE TITLE
Gamestream over internet issue

### ISSUE THREAD

**Issue by jtw6501** [moonlight-stream/moonlight-android#203]
I am able to gamestream from my p.c. to my note 5 over lan, but i can not get the over internet streaming to work. I have tried to forward the ports required, but i am not 100% sure i did it correctly.

**Comment by cgutman** [comment]
Can you screenshot your router port forwarding configuration page?

**Comment by BingoFishy** [comment]
I'm having the same problem. Here's a screenshot of my port configuration on a verizon router. I haven't done a whole tone of port forwarding, so I'm new to this stuff - tell me if I'm doing something wrong.

![image](https://cloud.githubusercontent.com/assets/10874365/15165180/c3109282-16e1-11e6-8eaa-9520170a70f5.png)

**Comment by cgutman** [comment]
It looks like you're missing UDP 48010. There should also be an IP address of your PC specified for each entry if you're using port forwarding.

**Comment by BingoFishy** [comment]
I'm getting the error: Failed to connect to \192.168.1.165 (port 47984) after 3000ms. 
So I ran PFPortChecker, and whaddaya know...
![image](https://cloud.githubusercontent.com/assets/10874365/15167903/9464aa0e-16fa-11e6-9712-8f395575cce0.png)
Also, when I'm connected to Wi-fi, now I get a blank screen and "The connection was terminated." so that's a no-go too as of now.
