### ISSUE TITLE
Mouse scaling potentially wrong?

### ISSUE THREAD

**Issue by jeid64** [moonlight-stream/moonlight-android#226]
Hey!

Just wondering if mouse scaling is supposed to work like this. On https://github.com/moonlight-stream/moonlight-android/blob/master/app/src/main/java/com/limelight/Game.java#L78 a 1280x720 constant resolution is set for the streams reference resolution, which is then used at https://github.com/moonlight-stream/moonlight-android/blob/master/app/src/main/java/com/limelight/binding/input/TouchContext.java#L78 to divide by the targetView resolution. On my Nexus 6, this always causes xFactor and yFactor to be .5, as it's always 1280x720/by screen's resolution. This seems like unintended behavior, because if I set the streams resolution to 1080p or 4k, the scaling is always the same.

It seems like REFERENCE_HORIZ_RES and REFERENCE_VERT_RES should be equal to prefConfig.width and height, so that the scaling is actually what the streams resolution is. In the IOS app, it uses the streams resolution and not 1280x720. https://github.com/moonlight-stream/moonlight-ios/blob/1783abec1351ccd7b101307eb536b0e74e91b014/Limelight/Stream/StreamManager.m#L82

**Comment by BetaLeaf** [comment]
I also have this issue. Please Fix!

**Comment by infernalshade** [comment]
+1! I also have this error. This issue is causing an offset on the mouse position in the stream (i can see the moonlight cursor (circle with outline) and the native one of the host machine, and they don't match. This wouldnt be a problem if i could install the root moonlight version on my Fire TV, but FireOS 5.2.1.1 is currently not rootable, so i don't have the option for it (The Problem is i cant go "off-screen" with the cursor, so i cant reach any controls/buttons at the edges of the screen)! I think the fix could be as easy as to use the configured resolution instead of a fixed one (like jeid64 already mentioned).

I'm looking forward to play my Strategy Games on my Living Room TV in the future :-)

Thx for all your work, btw! :-)

**Comment by renebohne** [comment]
I experienced the same problem on a fire tv stick 2.
