### ISSUE TITLE
Working on a Chromebook?

### ISSUE THREAD

**Issue by dvdmuckle** [moonlight-stream/moonlight-android#23]
Quite recently, a hack was discovered that would allow one to run basically any app in the Android runtime on a Chromebook. Under this hack, Limelight works in that it can boot up, though I have not been able to pair my PC on either my Acer C720 Chromebook or my Droid RAZR Maxx, though the Droid almost worked, but I since reinstalled the app and it now no longer will pair. I was able to connect using a Windows 8 computer on the same network, so the issue is with the app itself.

**Comment by lzap** [comment]
Any updates?

**Comment by cgutman** [comment]
I just tried it on Chrome 47 on Windows 10 and it seems to have regressed even more due to changes in ARC. They seem to have removed the OMX.ARC codecs that utilize hardware acceleration. Moonlight no longer includes the FFmpeg software renderer (since the performance is bad and it bloats the APK size), so Moonlight can't stream at all.

**Comment by cgutman** [comment]
Moonlight has a native Chrome plugin now - https://github.com/moonlight-stream/moonlight-chrome

**Comment by lzap** [comment]
You guys are rockstars. I hope it will work on ARM :-)

**Comment by cgutman** [comment]
It does :)

You can try the latest alpha if you want - http://forum.xda-developers.com/showpost.php?p=66756076&postcount=3471
