### ISSUE TITLE
Streaming over internet causes a loss of data

### ISSUE THREAD

**Issue by ShawNMusliM** [moonlight-stream/moonlight-android#233]
Sorry to keep bothering you guys but now that my phone connects and shows picture fine I'm having an issue holding he connection. After a minute or so moonlight, and I'm assuming this is moonlight causing this, shuts my data connection off. Then it tells me connection terminated. I then have to put my phone in airplane mode and then take it out of airplane mode to get data back. I never lose data like this unless I am streaming using moonlight.

**Comment by cgutman** [comment]
What happens if you lower the bitrate to the minimum value and try 720p 30 FPS?

It may be your cellular provider performing some sort of throttling. Alternatively, Moonlight may be exposing a bug in your phone's OS or cell radio firmware.

Moonlight doesn't have any sort of access that would allow it to affect your cellular connectivity. That would be a serious vulnerability if it could.

You can try contacting your carrier to see if they have some explanation.

**Comment by mrb113** [comment]
Closing as the issue is external to Moonlight
