### ISSUE TITLE
Keyboard Arrow Keys don't work

### ISSUE THREAD

**Issue by BetaLeaf** [moonlight-stream/moonlight-android#252]
So here's the issue. When I connect a USB or Bluetooth keyboard to my phone, the arrow keys do not work in moonlight.

**Comment by xperia64** [comment]
I was about to report the same thing.
I believe I know why at least bluetooth keyboard arrow keys don't work.
For whatever reason, Android interprets keyboard arrow key presses as gamepad D-Pad presses rather than actual keyboard arrow key keycodes. Moonlight needs to interpret gamepad D-Pad presses from a bluetooth/usb keyboard and send them as keyboard keycodes rather than gamepad events. The official Shield Hub client seems to do this correctly.

**Comment by Ziflin** [comment]
Is this something that can be fixed? It seems like most other useful keyboard keys (Ctrl+X/C/V etc) are working fine. Or has anyone found a way to get this to work with a bluetooth keyboard? Thanks.

**Comment by cgutman** [comment]
Give this build a shot: https://drive.google.com/open?id=0B_5O1xNt8Q9lQk1OcENLLWp4c28

**Comment by Ziflin** [comment]
Awesome thanks! It might take me a couple days to test. I'm about to hop on a plane.

**Comment by BoogeymanJones** [comment]
I tried the dpad-fix2 build and the numbers work perfectly. 
However, would it be possible to get these keys working as well?  /, *, +, and decimal "."
I am using a USB Numpad and I've tried several devices and multiple apps to try to remap the unrecognized keys, but the apps require changing the default android input method. Then the game will not detect the keyboard at all. Yes i realize a full keyboard would work, but I can fit the numpad in 1 pocket and the mouse in another :)
