### ISSUE TITLE
ERROR 521 With GFE 3.0.x

### ISSUE THREAD

**Issue by Inrovero** [moonlight-stream/moonlight-android#285]
_**Hi everyone!**_

Moonlight app, at least on my phone (Galaxy S6 edge), it not start any game with the new update of GeForce Experience... (version 3.0)

**Do you know something about this?** I can connect my phone to the GameStream, but when i click any game to start it, in my phone i get the message "Establishing Connection", **in my PC nothing happens (not start any process or something like that)**, and then i get the message **"GFE error: Streaming session has failed to a streaming error (Error code: 521)"**

With the older GFE it works well but **i can't use an older** version of GFE, NVidia just not let me do it..

**_I post my logfile here.._**

Thanks everyone!

[NvStreamerCurrent.txt](https://github.com/moonlight-stream/moonlight-android/files/512652/NvStreamerCurrent.txt)

**Comment by cgutman** [comment]
That's all the log you get? Usually there's far more than that. Can you try again?

**Comment by Inrovero** [comment]
I've tried again! But the new log replace the old log, and the old log keeps in a new file, when i try it again, the newest replace the old, the old replace the oldest, and the oldest it's missing..

**Comment by Inrovero** [comment]
Hello again, i've updated the Moonlight app and try it but i'm getting the same error that i had with GFE 3.0...

Any help?

**Comment by cgutman** [comment]
You'll probably need to downgrade to GFE 2.11 in order to play. It looks like the 3.0 streamer is crashing on your machine.

**Comment by deagon88** [comment]
Apologies for the necro but (for future googlers) i had this issue on windows server 2012 r2 using moonlight desktop on arch linux. In my case it turns out i needed to install QWAVE (Quality Windows Audio Video Experience) in the servers features before geforce experience would work. I've not used windows desktop for a few years so i cant remember if it can be uninstalled by the user through add/remove windows features. I spotted the solution in someones post on xda-developers.com but i've lost the link.

**Comment by aanuj96** [comment]
i fixed it ... its due not properly NVIDIA app components removed or not restart after unstinalling NVIDIA app which can lead to not completely remove somethings .. so to fix its simple uninstalling driver and Geforce experience and restart computer then install 1st geforce experience test moonlight and then update the driver ..
