### ISSUE TITLE
Mouse Offset when streaming resolution differs from native client resolution (severe)

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-android#329]
There seems to be a "severe" bug with the mouse offset in Moonlight, particularly when the streaming resolution differs from the client's native screen resolution. In my case:

I recently bought a 4K Sony Android TV. The app it-self works flawlessly and good as long as you don't use a external mouse. I know that there will always be a double cursor (as long as the device is not rooted). I can live with the double cursor, that's not a big deal to me - the problem is, the double cursor is way offset compared to the host's mouse cursor, which makes it impossible to play any games at all which require mouse input/support, like Elite Dangerous, Command & Conquer, Battlefield, etc. etc. You can never reach the full dimension of your host's screen.

It seems to me, that there is something wrong in the up-/downscaling calculation of the resolution. The larger the difference between the native and streaming resolution is, the bigger the gap and the offset.
Unfortunately, I cannot stream in 4K (which would solve the problem), so I stream at 1080p 60Hz to a 4K device and here the trouble begins.

This "needs" to be fixed, otherwise the app is pretty much unusable when it comes to mouse input/support, as I'm personally not willed to root and maybe brick my brand new Android TV, if you know what I mean ;-)
The same happened to me in the Java Legacy version - in that case I was to able to add the 768p resolution to the source code, which solved my problem (laptop native resoultion = streaming resolution = 1366x768p).

Other Streaming apps, for example TeamViewer don't have that kind of problem. In TeamViewer there's also a double cursor on my Android TV, but the double cursor is 100% aligned with the streaming cursor.

I would be very happy, if this bug can/could be fixed. To be honest, one of my reasons I bought the "Android" OS TV is, that I wanted to stream games via Moonlight to the TV.

Looking forward to a reply and hopefully to a fix/workaround :-).

This is really a awesome app, I love it, when you exclude the mouse cursor issue(s).

**Comment by pr030880** [comment]
Okay, I just re-checked and tested the double cursor thing with TeamViewer and randomly switched screen resolutions (720p, 768p 1080p) - the double cursor is always aligned with the host PC mouse cursor. This should also be possible in Moonlight. That's why I really think it's a bug within Moonlight it-self.
Direct Mouse Capturing - okay... isn't working without "root"-access, but that's not the point here.

What do you think Cameron and or Team - do you think that you guys can take a look at this bug?
You would make me and I think a couple of other gamers very happy, if this issue could be solved :-)

**Comment by pr030880** [comment]
I was able to test 4K with Moonlight and the mouse is offset as well compared to the double cursor.
Besides TramViewer, I also tested Remotr and KinoConsole. They don't have this kind of issue with the mouse, but they are not as performant as Moonlight.
In my opinion Moonlight is "the best" streaming app outthere, but with the mouse offset issue currently unusable for me and others without root.

**Comment by cgutman** [comment]
Unfortunately this really isn't possible for us to fix without a new Android API or a change in the GameStream protocol. Other streaming solutions have options for absolute mouse movement (move to a point) but GameStream only has relative mouse movement (move up/down/left/right some number of pixels). It's impossible for them to always stay in sync, given mouse acceleration, host mouse speed, and the initial starting position being unpredictable. There's just not an API to do that in Android since mouse devices aren't commonly used enough.

In Android 7.0, it's a bit better since there's a new API to hide the cursor and get relative mouse movement. It's not ideal because the mouse loses focus over the navigation bar and status bar on phones and tablets. For TVs, it may be perfect since there's no navigation or status bar to interfere. I guess you should wait for your TV to receive an update to Android 7.0.

**Comment by pr030880** [comment]
Hi Cameron,
thanks for the feedback, much appreciated :-). What a pity, but I guess I'll gonna wait 'til Android 7 will hit my device.
The relative mouse movement and hide cursor option you mentioned for Android 7, is that possible without root on my TV, if I got Android 7? Do you know if it is/will be a particularly option in a future Moonlight build or from the OS it-self...

Many thanks for your efforts :-)

**Comment by cgutman** [comment]
With Android 7, it's possible without root. Moonlight already supports the new mouse features of Android 7, but your device has to be updated for those to work.

**Comment by pr030880** [comment]
That sounds awesome - thanks for your help on this :-)
You have a nice week/weekend.
