### ISSUE TITLE
Pale colors for titles or additional information

### ISSUE THREAD

**Issue by qualityghost** [moonlight-stream/moonlight-android#341]
Some game elements like a HUD or titles are displayed in pale colors. It looks like "layer" with additional game information is displayed with poor colors, game "layer", (I mean textures) looks fine. This issue occurs for all my games independently from my TV colors settings. My TV: Philips 55PUS6501/12, GFE version 3.3.0.95, Moonlight  v4.8.3.

**Comment by qualityghost** [comment]
I noticed that issue occurs when game streaming resolution is set on 1080. When resolution is set on 4k then colors are OK.

**Comment by Trasen** [comment]
Is it possible that you have some filters active on the TV?

Frame interpolation or some active HDR function?

Is the issue there when you are just steaming the desktop at 1080p?

**Comment by qualityghost** [comment]
I have active HDR function and probably nothing else. Colors look natural during watching Netflix or YouTube also color of subtitles is ok for those app.

Yes, issue exists also during streaming the desktop at 1080, icons colors look pale e.g. for Firefox, but wallpaper looks fine. It is very noticeable for red, orange and yellow colour.

I'll do some tests with HDR on/off also I'll check my filters settings and let you know about results.

**Comment by Trasen** [comment]
Please do.

Could you also try doing some streamig from a different device to the same streamer/ computer? Just to exclude any issues from the computer.

Try to get the TV out of the equation, it's a safe bet to assume that there's something causing chaos there, unfortunately.

**Comment by qualityghost** [comment]
TV:
I did tests with HDR on/off, ultra HD on/off - no differences. I also on/off some filters related with view - no difference and finally I checked TV pre-setting mods like personal or game - no difference. Of course after changes game textures look darker or lighter and so on but issue with colors still occurs and is very noticeable.

Moonlight:
Issue exists during streaming at 720/1080p 30/60 fps, with H.264 or H.265 selected to stream. 

Everything works great for 4k 30/60 fps.

Game settings:
Mostly I did test with Witcher 3 and when 4k/60Hz is set in Moonlight I can change game resolution (in game settings) during streaming on 1080p and fps limited to 60 so my graphic card can easily work stable and generates 60 fps with game ultra settings and then colors are OK! But average frame decoding latency remains like for 4k setting and is around 40-45 ms. When 1080/60 fps is set in Moonlight and in game settings then average frame decoding latency is around 26-29 ms for my TV but colors are pale, time lag between those two settings is noticeable during streaming. One more when I try to change gamma setting in game options I do't see any differences on my TV screen.

PC: 
Unfortunately I haven't possibility to stream to my game computer but last I installed new operating system and currently I have Windows 10 Pro 64bit. Previously I worked on Windows 8.1 64bit and issue occurs on both systems. If that helps, this is my PC configuration: processor i5 4590, 8 GB of RAM - 1600 MHz, graphic card msi gtx 1070 gaming z.

**Comment by Trasen** [comment]
Hey man,

Yeah i mean that's the issue - the common culprit in this is that you're having issues on the TV. This is why it's so important to check with a different device.

Since the issues is only pressent on a non-native resolution i just have to assume that the TV has some kind of automatic scaling filter which is causing the lack of color in the picture.

I've not been able to find anyone else with the same, or even similar issues. Just as an experiment, could you change the bandwith settings on 4k, setting it to a lower value (rought 10-20mbit lower than standard) and see if the picture lacks color-data?

Same with 1080p, put it on higher and lower settings and see if there's any change in the collor pallet.

However, bottom line is that there's technicly shouldn't be anything in Moonlight controlling these things, if anything might be the culprit it's the codec on the TV fiddeling with the frame saturation on lower resolutions.

Let's see if we can get a comment from Cgutman, he might have an idea of what might be causing this behaviour.

**Comment by qualityghost** [comment]
Hey Trasen, thank you for the quick reply.

I did tests with Nexus 6P and it looks like my TV has issue with colors in non native resolution. Nexus resolution is 2560x1440 and colors are good no matter what is selected in Moonlight 1080 or 4k.

I also changed bandwidth on my TV for 1080 on higher and issue still occurs. For 4k and lower bandwidth, only image quality is poor, colors are OK.

Additional info is that my TV works with android 6.0.1 and nexus with 7.1.2.

**Comment by qualityghost** [comment]
Yesterday I did additional tests with video streaming from my PC. I prepared video samples coded in h.265/1080/60fps and my TV hasn't any problems with correct displaying these samples using default video player. 

Kodi displays video with lower resolution using scaling and everything looks fine. 

Issue with colors occurs only for Moonlight and 720 or 1080 resolution selected to stream. 

Should I report this issue to Philips Support?

**Comment by Trasen** [comment]
Hey man,

Yeah but you're still streaming, that's the issue. Moonlight adapts to a 1080p resolution when settings are at 1080, hence : It's an active lowering of resolution, not a passive one as in Kodi. Is there a setting on the TV that let's you manually change the renderer to 1080p? Maybe in the Android TV-interface?

It would be a good thing to try out, however this is most likely the last idea i can come up with.

Well since Moonlight is the only app you're having issues with (supposedly), contacting Philips will only result in the same stuff we've been going through here - i would wait for Cgutman to see this thread where we can get a definitive answer.

But try what i suggested above :)

**Comment by qualityghost** [comment]
Hi,
some time ago my TV software has been updated to version 7.1.2 and issue with colours still occurs for 1080p.
