### ISSUE TITLE
high latency with amlogic s912

### ISSUE THREAD

**Issue by spellozz** [moonlight-stream/moonlight-android#347]
hi. I tried to use android tv box with amlogic s912 (x92) ,and I got about 120 ms latency over lan and roaming enternet. When I use shield tv, samsung s6, I got ~ 1-5ms. With  Alcatel POP 2 5042D(Qualcomm Snapdragon 410) I got ~30ms. It's a hardware problem or firmware issue? I read that another amlogic s805 have the same issue.

**Comment by lazarevski** [comment]
Same here. I have the [MXIII G II](http://www.gearbest.com/tv-box-mini-pc/pp_580667.html) tv box and i experience 100-200ms lag. When i steam to Samsung Note 5 i get around 5ms.

**Comment by Trasen** [comment]
Got a Mini M8S ll (2) with the same issue now. Worked like a sharm just a week ago with lat on less than 20, now never below 70.

Did something happen with the latest Nvidia driver or?

**Comment by Trasen** [comment]
I solved this by re-installing the Nvidia drivers, at least the general frame rate issues  (down to 27- 35ms).

How's the performance on the S912 atm?

**Comment by DamianoErnesti** [comment]
Was there any progress on this matter? I'm considering buying a Beelink GT1 and flashing a custom rom on it, everything looks good but this, and Moonlight is a pretty big deal to me.

**Comment by LaBoss** [comment]
i have same issue with a Beelink GT1 Ultimate, on IOS my latency is 15/20ms on GT1 is 100/200ms

**Comment by Hegom** [comment]
I still have the same problem, with my galaxy J7 2016 Mali-T830MP2 I have like 20ms of latency but with my android tv box with S912 I have 70ms of decoding speed.

**Comment by OrangeDog23** [comment]
found some info in master branch:
    //MediaCodecHelper.java p 128
		// These theoretically have good HEVC decoding capabilities (potentially better than
		// their AVC decoders), but haven't been tested enough
		//whitelistedHevcDecoders.add("omx.amlogic");
		//whitelistedHevcDecoders.add("omx.rk");
Looks like H265 disabled for our chip.

**Comment by Creazawolf** [comment]
I have a Alfawise H96 pro + with S912 and have the same latency Issues, I get around 90-110 ms on 1080p - 45 mbs, Thats about the lowest I can go. Really hard to take good corners in F1 2017 haha. Anyway. . Would be so nice to have h265 capabilities on this chip.. 4k is not a problem for it.   Instead Im streaming to my RaspberryPi3 without any hickups and problems and thats great but the Pi is ofcourse limited to 1080p with not to much of video bandwith, because of its hardware.

Please let us know if you have some news on this chip in the future.

**Comment by apoklyps3** [comment]
any update on this , was thinking about buying an AMlogic S912 powered box for moonlight, but it seems it is not a good ideea...

**Comment by tournierjc** [comment]
Hello,

I've recompiled the app with HEVC Decoder for amlogic enabled.

You can find it here : http://uptobox.com/t3pqoq0xipx0

Tell me if it's better for you. I've been able to play in 4k 60fps with 30ms latency. Has been a bit laggy sometimes, probably because I'm streaming from a wifi 5ghz connected computer.

**Comment by apoklyps3** [comment]
anybody tested?

**Comment by tournierjc** [comment]
Hi apoklyps3. 

Which box are you willing to buy ? I do not have any issue anymore with my EgoIggo S12 Pro box.

The feedback of other people with their box' name should be interesting, we could ask to allow our Amlogic decoder in the official app...

**Comment by apoklyps3** [comment]
something similar (with s912 or s905). there are going to be alot of deals at gearbest soon.
can you test the latency @1080p/60fps? 
thanks

**Comment by Hegom** [comment]
Hi @tournierjc ,

Now I have a 1080Ti that have support for H265 decoding, and I'm having 30ms of latency on any fps and resolution, but If I change to H264 I'm getting 70ms of latency, with your app I will be able to have low latency using H264 decoding? I want to see those latency numbers(~5-10ms) that I have on my phone and other devices on my tv box.

In summary will be great if we have 2 options depending on the game.

- H264 and very low latency @1080p
- H265 with 30ms of latency @4k

**Comment by apoklyps3** [comment]
Hi @tournierjc . Can you build the latest version version with amlogic support or at least point me on how to do it myself?
I won a meecool box s912 in a giveaway and should be recievieng it soon.
My expectations are very low with it as I have tested moonlight for android on my galaxy note 4 and even though decoder latecny is as low as 9ms, the stuttering I get is a deal breaker. enabling stutter fix brings way to much controller lag to be a viable option. but hey, the box is free...I'll give it a go.
really bummed though. was under the impresion that the android version is the advanced one...

**Comment by cgutman** [comment]
You don't need a custom build to activate H.265 for non-whitelisted decoder hardware. Just go to Settings -> Change H.265 Settings -> Always use H.265.

Each platform has its advantages and disadvantages. Android is one of the richest platforms in terms of APIs and features, but difficult to develop for due to many inconsistent implementations by device makers. This is why we have to have things like these blacklists and whitelists for decoders on Android, while on iOS, we can just trust that if Apple says it supports HEVC, it will work.

**Comment by apoklyps3** [comment]
had high hopes for the Mecool M8S L box I have won in a giveaway.
They were quickly shut down once it arrived.
Performance is atrociuous and the stuttering is unbareable even with the fix applied.
This is on both wifi and LAN connections.
it kinda works with 720p30fps, but it still stutters from time to time.
has this stuttering been with s910 devices forever or some version introduced it?

**Comment by tournierjc** [comment]
Hello,

Do you have Android 6.0? I have noticed issue with Android 7.1.2 as the
video driver isn't really good.

Le 12 déc. 2017 12:58 PM, "apoklyps3" <notifications@github.com> a écrit :

had high hopes for the Mecool M8S L box I have won in a giveaway.
They were quickly shut down once it arrived.
Performance is atrociuous and the stuttering is unbareable even with the
fix applied.
This is on both wifi and LAN connections.
it kinda works with 720p30fps, but it still stutters from time to time.
has this stuttering been with s910 devices forever or some version
introduced it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/moonlight-stream/moonlight-android/issues/347#issuecomment-351031029>,
or mute the thread

**Comment by apoklyps3** [comment]
it came with 7.1.1 Android TV firmware and then I have updated to a custom Nexus Rom wich has 7.1.2 regular android. Really hated ATV interface

**Comment by Hegom** [comment]
Past week I saw an update for Moonlight:

WHAT'S NEW

_v5.6.1
- Fix H.265 streaming on Amlogic and MediaTek SoCs
- Improve decoder compatibility with H.265 streaming
v5.6
- Fix crash at 1080p on Snapdragon 200 and 400 series SoCs
- Restrict streaming resolutions to those the decoder supports
- Rework internal decoder logic to increase reliability
- Minor multi-window and PiP fixes_

I was expecting a better performance but it makes the application totally unusable at least in my case that I use a KM8 Pro Amlogic S912, If I select 4k 60fps in the streaming resolution and H265 for the decoder I'm always getting the error "Unsupported resolution" or something like that, and I also have the same 70ms of latency on H264 which I know isn't part of the update but will be good if the latency is lower using H264.

**Comment by apoklyps3** [comment]
don't really understand youtubers that test android boxes say that s912 are really good for moonlight. 
are we doing something wrong? is there a special older version they are using were things are not broken?
so far I found the best solution for decent game stream si to have... another decent computer (laptop), but not even that assures portability as a android box does when you are travelling alot.
the stutter issue we are encountering on android is nowhere to be found on an pretty old i5 M460 with 4GB DDR3 and Nvidia GT420. I know this is computer, but to me it seems that mobile solutions such as the Mali GPU integrated in android boxes should be more capable in video deconding than such a old GPU

**Comment by HewellP** [comment]
Hi! Yesterday I receved my s912 device, a Vorke Z6 Plus, with 3GB DDR3 and 32GB for 50$ in geekbuying.
After advertising, I just say than I have 40-60 ms for H.264 and H.265 with 1080p@60.
It's enough latency to be perceived but i'ts low for games like Deus Ex or Tomb Raider.

**Comment by nLLIeHu4ka** [comment]
i have ugoos am3 ... on official rom i had 35 ms latency, but every 5 seconds i see microlags and it not comfort for me... Now i flash custom rom android tv and i have 50-58 ms latecy but without lags... it seems big problem in drivers for gpu and roms i think... for comfortly game need 20 ms and less.. but how its make i dont know... try may roms 6 and 7 android)

**Comment by nLLIeHu4ka** [comment]
better performace (lower latency) on mediatec android box - xiaomi 3 enhaced... on rockchip i dont now... i think all android tv box bad for moonlight (only nvidia shield =)  )...

**Comment by HewellP** [comment]
well... that is not a fix but the lauch of steam app in android could help anyone to a better stream with this CPU

**Comment by Hegom** [comment]
Yes, that is a very good news, I already sold my android device, guys please keep me updated, that could encourage me to buy the same device again

**Comment by NewUser9** [comment]
Still high latency on s912 chipset (Neelink GT1 Ultimate)
App Version - 8.7
H264 Decode latency - 50-60ms
H265 Decode latency - 30-40ms

All test were done at 1080p resolution.
