### ISSUE TITLE
Both client and host use gamepad

### ISSUE THREAD

**Issue by ChetahPangestu** [moonlight-stream/moonlight-android#358]
My mate and I are trying to play Resident Evil Revelations 2 splitscreen Co-Op via Moonlight and I am hosting the stream. 

Is there any way that both of us can use a gamepad each on our respective PCs?
Whenever my mate is using his gamepad, I lose all control to the game and have to restart the stream for me to regain control. I have tried to renamed the .dll file to .old but that completely removes his gamepad control.

While I am at it, whenever I am hosting the stream, I lose all audio of the game and only the game while everything else is fine.

We have tried almost everything to make this work but to not avail. 
Any help will be greatly appreciated.

**Comment by Trasen** [comment]
Technicly, since this functionality is present on Nvidias Game stream, it definetly should be possible. Could you try to launch the game from Steam and manually configure the controllers from there? Big picture mode > settings > Controllers, and make sure that only Xbox controllers are ticket, none of the others.

Steam can change the HID translation of the connecting controllers to Xinput, and should theoreticly be able to pick up both the connecting and the connected controller/s.

I will try to see if this is possible on my own rigg when i find the time for it. Not a proper solution but at least it should work as a make-shift workaround.
