### ISSUE TITLE
Audio bug with Fallout 4

### ISSUE THREAD

**Issue by sirenianprime** [moonlight-stream/moonlight-android#365]
Whenever I stream Fallout 4 through the Moonlight App, I get a horrible ear piercing static in place of the music. All of my apps and drivers are up to date, and I have tried on 2 different android devices and an iPhone. Is there a known solution for this? I cannot find any info on it.

**Comment by sirenianprime** [comment]
It's been a year and 4 months. I sure as s*** am glad that I didn't have to rely on support from this site. SMFH

**Comment by cgutman** [comment]
Moonlight is done in my free time after work and I'm often the only one looking after the project and all the reported issues (many of which are just configuration errors or GFE issues and not Moonlight bugs), so unfortunately some issues languish like this. We've started a Discord server recently to make it easier for the community to help users.

What bitrate are you streaming at? Are you still only seeing it in Fallout 4?

With GFE 3.14.1 (released 7/23), you'll get static at bitrates <= 5 Mbps. I have a fix for that which I have been delayed on rolling out due to another gamepad hotplugging issue introduced in the same GFE release.

**Comment by thw0rted** [comment]
@sirenianprime do you not understand how open source development works, or are you just always incredibly rude? If my kids "asked for help" like this they'd be grounded for a week.
