### ISSUE TITLE
Severe Audio Latency

### ISSUE THREAD

**Issue by Gamer9** [moonlight-stream/moonlight-android#370]
Hello, I am getting a very strange issue where the Audio is running at a significant delay which pretty much ruins the whole experience.

The audio being delayed and out of sync is easily noticeable but rather than give a rough estimate of what I perceive to be a half or quarter second delay, I thought I'd measure the difference between the host and client and it's around 300ms (290ms to be a little more exact). The measurements are for 1080p@60fps H.264 but the same issue is there also with H.265 and at 720p@30/60fps.

I'm not sure why this would happen as the Video runs at 16ms latency according to Moonlight Android and is indistinguishable between the host and client.

I'm running Android OS 6.0.1 with Moonlight Android v4.8.3 and GFE v3.5.0.70 on W7.
Also tried with combinations of  Moonlight Android v4.8.2 and GFE v3.4.0.70 on a different W10 host machine, and with both 2.4GHz and 5GHz connection with the router fairly close by and still have the same issue.

I don't think this is a hardware issue per se as other streaming services like YouTube run just fine on Snapdragon 617/ Adreno 405, but could Moonlight Android interact differently with this SoC?

**Comment by Trasen** [comment]
Hey Gamer9,

What device are you running?

Best regards!

**Comment by Gamer9** [comment]
Hello Trasen,
Thanks for the reply. This is on an Alcatel Idol 4. Do you by any chance have this device and can check to see if this is an issue with this particular device? (or perhaps others can if they have it). Or is it a known issue that happens on other devices too? I don't see why it should happen as the Moonlight stream actually runs perfectly smoothly on it, barring the audio latency.
Any advice you can give would be appreciated.
Thanks.

**Comment by Trasen** [comment]
Hello again,

No unfortunatly i don't, generally moonlight runs very well on Qualcom chips. However you've tried on two different machines and that does break down the issue coming from the Phone itself.

Just as a reference-check, see if you can find a different phone/ android device and stream from the computer/s just to confirm that the issue is from the phone.

Also, are you streaming with 5.1 or stereo sound? If 5.1, try un-ticking that option.

Let's see if someone else comes in having similar issues, since atm there's no active user having this problem (as far as i can see).

**Comment by a-lame-username** [comment]
Hi guys,

Just started experiencing this issue. 5.1 audio is off, and I'm running a Samsung Galaxy S5 w/Cyanogen, although I would've said it's more like almost a full-second delay.

Just updated GFE - I think it's improved - delay is more like OP was saying.

I think it may be a network issue, since I was on a different LAN a couple of weeks ago (when I last used Moonlight), and did not have this issue. Just tried it on my new LAN, and I'm having the issue, although it seems unlikely, since controller/video streaming still run beautifully. Has there been an update to Moonlight in the last week or so that would've changed audio decoding/encoding at all?

**Comment by Gamer9** [comment]
Hello Trasen, My issue is definitely the phone with Android 6.0.1 / Snapdragon 617 SoC as I have tested other devices with different Android / SoC that do not have this audio lag. Thanks for trying to help. It's much appreciated.

**Comment by Gamer9** [comment]
Hello a-lame-username, a full second audio delay would be unbearable as even the quarter second+ delay I'm getting is terrible. I don't think it's a network issue for me as I tried on 2 networks with same problem even though the video streaming is near real time. The latest Moonlight is 4.8.4 from the day of your comment which still shows the same issue.
Compared to my issue on Snapdragon 617, your Samsung Galaxy S5 has a different SoC with Snapdragon 801 and Adreno 330, but both are similarly sufficient for 1080p decoding. The S5 updated to 6.0.1 Marshmallow and I believe Cyanogen is based on 6.0.1 so I wonder if that's where the problem is for both our devices. Maybe others with Android 6.0.1 can comment?

**Comment by Biznut** [comment]
Hey guys, this thread is a few months old but I just wanted to give some of my experience on this issues.  

So I pretty much have the same exact issue where the video feed is almost perfectly in sync with the computer, but there is a severe audio lag.  And I can confirm it is definitely not an issue with my network, if I listen to the audio off my computer it perfectly matches the video feed on my phone with no slowdown or stuttering.

I'm using the latest Moonlight v5.2 and Gamestream at the time of writing this running off of a Samsung Galaxy S5 using the latest 6.0.1 stock rom.  To see if it is an issue with Marshmallow I downgraded the phone to 5.1.1 Lollipop, but the audio lag seems to be unchanged.  I could try different version of the Lollipop, but I somewhat doubt it'll make much of a difference and I don't want to downgrade my phone any further. 

Some more info, my PC is running of a GTX 970 with Driver Version 385.41.  

I might try this off of my siblings pc's (they have a GTX 660ti and GTX 760)  And also try using my brother's Moto E4 to see if this might be an issue with the GPU, or if its just the Galaxy S5 that is causing the problem.

**Comment by InanimateCrbnRod** [comment]
Same issue. Audio is more than half a second delayed. I just bought a new cat 7 50ft ethernet cable and it didn't fix the issue. Video looks great but unfortunately I won't be able to stream. It would be great to add a feature to manually adjust A/V sync

**Comment by cgutman** [comment]
The report here is ancient (Android 6.0/5.1) and no longer relevant. Please open a new issue if this is still a problem. Provide the version of Android, GeForce Experience version, Nvidia GPU driver version, how you tested (including the game/app you used on your PC), audio output device in use (Chromecast, Bluetooth, wired headphones, etc), Windows version, and anything else relevant.

Manually adding video delay to sync up with audio would make the game unplayable, so that's not going to be implemented.
