### ISSUE TITLE
DualShock 4 native mode for Steam

### ISSUE THREAD

**Issue by thealex626** [moonlight-stream/moonlight-android#371]
Hey guys! I'm using Moonlight on my Fire TV with DualShock controller.

However for some games I want to use DualShock 4 controller in PS4 mode for its build-in touchpad together with Steam Big Picture and "Support PS4 controller" option enabled in Steam. I need the inputs not to be converted into Xbox360 controller inputs. I set up the Steam controller profile with DualShock 4 support, and I'm using the DS4 touchpad for extra controls - left part of touchpad is for touch menu, right part is for the mouse control. This is very useful for playing classic games that doesn't support controller at all: Half-Life, Half-Life 2, Far Cry 1 and etc. It's okay when I connect directly to computer. But when I do the same with Moonlight, Steam detects it only as Xbox controller... So no touchpad support and I can't customize it at all. And I didn't find the way to switch off the conversion. 

Please, I beg you, add the option "Support DualShock 4 controller" in Moonlight settings next to "Use XboxOne driver" to make it possible to send the DualShock 4 input controls directly to Steam.

Thank you very much for creating this awesome program!

**Comment by thealex626** [comment]
Anybody, please?

**Comment by Trasen** [comment]
Hey,

Unfortunately this seems to be impossible atm. I would suggest creating custom binds in these games for controller support.

Should definitely exist some guides if you Google it.

Best regards

**Comment by thealex626** [comment]
Is there any explanation for this being impossible? Why it couldn't send the DS4 commands over network, just like it does with Xbox controller? I want to use the touch-pad and a native DS4 support in Steam, and I couldn't customize it in current Xbox-controller emulation mode.

**Comment by Trasen** [comment]
Hey,

Because you're asking for native support for something that won't even run natively on Android. I'm using a Mini M8S 2, rooted and a custom firmware - including the Sixaxis driver app to make all functions of the DS4 to be carried over.

What the touchpad is translated  to is the touch controllers similar to when you're on Moonlight on your phone, hence : Mouse.

This is possible, but only if you root your device, which makes it a work-around. Letting steam change the device translation when the actual device on your PC when connected through Moonlight (Nvidia Game Stream) is a HID device with controller binds seems to be impossible. I've tried this to make CEMU work properly with no real success.

Best advice i can give though, since what you want to do is to actually run older games with no native controller support, would be to change the binds in those games. Alternativly use 3rd part software like XPadder to directly change which button is pressed when you press a button through moonlight.

Another alternative is to connect the DS4 to your PC instead of through Android, giving Steam direct access to the controller.

**Comment by thealex626** [comment]
Thanks for the explanation :)
Hopefully this will be possible some day.

**Comment by thealex626** [comment]
Hey, I have a good idea. Maybe it's possible to craft a tool that sends DS4 input into Moonlight-iOS app over WiFi, just like this: https://github.com/LiveFlightApp
