### ISSUE TITLE
Since Upgrading to Latest GeForce Experience (3.5.0.70) Getting Infrequent Major Stutter

### ISSUE THREAD

**Issue by MrScruff300** [moonlight-stream/moonlight-android#374]
Hi,

I use my Nexus 7 (2013) tablet to stream Steam from my desktop to my Nexus 7 tablet using the Moonlight play store app. Previously it has worked perfectly smoothly on 720p 60fps across my home network, however since the latest NVIDIA GeForce Experience Update 3.5.0.70 it has developed an occasional major stutter which makes games unplayable, incidentally it still steams fine without any issues via my Raspberry Pi and nothing has changed with the speed or setup of my network. When streaming on the Nexus it is really smooth for the first few minutes than seemingly randomly has a major stutter for a few seconds which makes the game unplayable then frees up to be smooth again, it repeats this pattern of freezing majorly every couple of minutes. It seems to be something in my experience only affecting the android version of moonlight and only since the latest GeForce Experience update. Can you look into this as at the moment it is unplayable?

Thanks!

**Comment by rzamoramty** [comment]
I'm having this issue as well, what is going on???

**Comment by rzamoramty** [comment]
Hey! Check this out and tell me if it helps you... while we wait for a fix D': 

http://www.filehorse.com/es/descargar-nvidia-geforce-experience/29427/

**Comment by MrScruff300** [comment]
Hi rzamoramty,

Many thanks for your suggestion, did this work for you? Always a little wary of installing a GFE not directly from NVIDIA, as worry about malware etc. So frustrating that NVIDIA don't keep historical versions on their website! What are you thoughts on installing GFE not sourced from NVIDIA?

Cheers!

**Comment by MrScruff300** [comment]
Just a quick update. Updated to latest GFE 3.6.0.74 and latest NVIDIA graphics drivers and still experiencing this issue! It streams so smooth on my Nexus 7 for a gd 5/6 minutes then there's a major stutter lasting a few seconds, picture freezes still but music still plays, then super smooth again until next major stutter a few minutes later. Any sign of a fix to the android version of moonlight? RPi version still working brilliantly with newest GFE. Thanks!

**Comment by rzamoramty** [comment]
Hi MrScruff300,

I trusted that site because it uses the link from NVIDIA to download -> https://us.download.nvidia.com/GFE/GFEClient/3.4.0.70/GeForce_Experience_v3.4.0.70.exe 

It did help with the issue, but is a pain in the... to use, NVIDIA tries to update no matter what; and if I block the nvidia services from accessing the internet, it creates a new set of problems. Also, i found that this version (3.4.0.70) had problems streaming a few of the newer games. So, to recap, this is not an elegant solution :(

I haven't tried the new GFE, I will try it out and check if the issue continues, like you said.

**Comment by MrScruff300** [comment]
Hi rzamoramty,

Did you get a chance to try the new GFE? Any better for you? Really hope this get fixed soon as the major intermittent stuttering makes games unplayable on the android version!

Cheers!

**Comment by rzamoramty** [comment]
Hey MrScruff300,

I've already checked out the new GFE. It has the same problem. I tried everything, but still, the intermittent stuttering is happening. I don't know what else to do. 

I hope they fix this soon.

Thanks!

**Comment by MrScruff300** [comment]
Hey,

Thanks for trying and letting me know! Fingers crossed we'll get a fix soon! I've tried everything too but no setting or network setups seem to resolve the issue.

Cheers!

**Comment by rzamoramty** [comment]
Any news? please keep me posted.

**Comment by MrScruff300** [comment]
Nothing yet rzamoramty, just waiting for a fix. If I do hear anything will let you know. Cheers!

**Comment by Trasen** [comment]
Had the same issue after the last update. Solution was the same thing as always : run Driver Sweeper (Google it > 3D Guru > You will be directed to the new version (New name) and run it in fail safe mode), this has solved similar issues in the past.

Just using Nvidias own 'clean install will not work.

Please try this.

**Comment by MrScruff300** [comment]
Hi Trasen,

Many thanks for the advice! The strange thing is it is working fine when using moonlight-embedded on my Raspberry Pi just the Android version that has developed this issue recently. If it was a driver issue on the PC would it not be affecting the stream to Pi also?

Cheers!

**Comment by Trasen** [comment]
Hey again,

Actually seems to only affect certain devices and not specific systems.

Example : S4 Mini 12 ms no stuttering, works perfect.

A5 2017 7ms Stutters every 3-5 sec, driver swipe fixed the stuttering while remaining the same on S4 Mini.

Same issue on M8S Mini 2, reinstalled Nvidia drivers worked (without wipe).

Meanwhile no stuttering what so ever on the Chrome Client.

So it's definitely worth doing, since the issue doesn't seem to be system related, but hardware. Most likely implementation differences in the different Mali/ ARM cores.

Would fix this myself if I knew how it was built :/

**Comment by JasonS7notG5** [comment]
@Trasen let me guess... S4 Mini and M8S Mini 2 are running an Android version before 6.0 Marshmallow while your A5 2017 is running Android 6.0+, am I right? Thats why you have micro stutters because Moonlight is broken for devices with newer Android versions, it doesnt matter which hardware you have or if you reinstall GeForce Experience etc.

**Comment by Trasen** [comment]
All of them are on 6.0 and for the A5 device the wipe reinstall worked.

You're jumping the gun in that thread you started. This issue might be connected to system-wide issue with certain hardware - sure.

But there are devices (a majority even) which works really well regardless of which version of Android it's using.

However, the issue you're having with the s7 seems to be very consistent, so yes, hardware related.

**Comment by MrScruff300** [comment]
Hi Trasen and Jason,

Thanks for your comments! Yeah, just to confirm this thread is not about microstuttering. Moonlight runs smooth as silk on my Nexus 7 for a number of minutes until it has a 'major stutter' for a good few seconds (where audio continues but picture freezes). Moonlight is then very smooth again for a few minutes until another major freeze. Also the operating system on my N7 has not changed when this error began. It was running perfectly fine before on the same OS, it was triggered after an NVIDIA GFE/Driver Update (current OS on N7 is android 6.0.1). Hoping for a fix soon. Cheers!

**Comment by JasonS7notG5** [comment]
I think Gutman said it is network related. I personally can say that I have micro stutters with my Razer Forge TV (Snapdragon 805, Android 6.0.1) and two S7 edges (Exynos 8890, Android 6.0.1 / 7.0). While on my other Android devices lower than Android 6.0 (plus before my Razer Forge TV updated itself from 5.1.1 to 6.0.1) I have not experienced micro stutters but input lag. "Ad-Hoc'ing" (I think this means USB tethering?) my S7 edge with my PC didn't fixed anything.

I said this before: Please use GameBench and show your results here @everyone. It will show your FPS (unfortunately not in milliseconds) on your device. I posted my [results here](https://github.com/moonlight-stream/moonlight-android/issues/349) (screenshots, video, etc.. it was very time consuming). It may be not 100% only Android 6.0+ related but this is what I experienced and no one proved me wrong.

**Comment by Trasen** [comment]
@JasonS7notG5 : Adhoc is a method of creating an acces point on your computers wifi, pretty much turning it to it's own router. Google it to see how you set it up on your version of Windows.

Gutman has actually already answered you  the 12th of April : "I never said there wasn't a bug. I've seen it with my own eyes. I've also spent many hours successfully reproducing the bug on my own devices.

My point is that I work on this project as a hobby in my limited free time. If it's not breaking almost everyone (like a new GFE update totally breaking streaming), it's hard to be motivated after working a 9 hour day at a real job, to sit down and work for another 6 hours on this issue.

As I said in email, I will continue working on it but progress is slow."

Hence : He is working on it, but it takes time.

"It may be not 100% only Android 6.0+ related but this is what I experienced and no one proved me wrong." - All you're saying here is that you're having issues, dissregarding the thousands of people not having problems with the software. Since none of the fixes the community has come up with works for you, you need to wait for a fix for the S7, clearly stated by the main-dev above.

**Comment by jaysharp29** [comment]
While I can't be sure of the technical underpinnings, I can confirm that on my moto g 3rd gen, using a lollipop Rom results in a perfect framerate with no frame pacing.  The upgrade to both marshmallow and nougot create stutter, but reduce latency.  Because my moto g gen 4 can't use lolipop, it's useless for moonlight at the moment. 

Essentially, until the issues are sorted out for these devices, buy the most powerful lollipop capable phone you can afford.  I bought the moto g 4 for diy vr, but have resorted to the 3rd gen for that very reason. 

My 2cents.

**Comment by rzamoramty** [comment]
Hi everyone!

Wow this post grew in a matter of days. I want to clarify like @MrScruff300, **this issue is not about microstutters**, but an issue with a 2-3 second stutter every few minutes. 

@JasonS7notG5 please don't turn this post in a discussion about your issue with microstutters, we are not talking about the same thing.

@MrScruff300 I did a few things in my router that almost resolved the issue, but not quite:
1. Enabled WMM on my 5ghz network
2. Changed the channel to auto (there aren't many 5ghz networks on my neighborhood, so I let the router to choose what's best)
3. Changed the channel frequency to 20/40/80 mhz (again, to let the router choose the best frequency)
4. Removed all the blockage that I can, between the router and my room, where I play the most 
5. Disabled location services on my phone, when I play (an s7 with Nougat)
6. Disabled sync services on my phone, when I play.

These 6 things managed to remove the erratic stutter to once every 20 minutes or so, not ideal but playable.

I guess the issue here is that moonlight can't manage temporal dips on signal strength like the nvidia and steam client does. When I play via steam streaming for example, and there's interference on my network, it simply reduces the image quality for a few seconds (without stuttering), a much better solution IHMO than skipping frames like a dancer.

I hope the developers have the time to address this soon (fingers crossed)

**Comment by jaysharp29** [comment]
I'm sure the issues are actually hardware specific to the way they interface with is after lolipop.  My two moto g phones exhibit different issues. The gen 3 on marshmallow starts off smooth and slowly deteriorates into insane stutter, then slowly smooths out again.  On lollipop it's smooth sailing for hours at a time.

The gen 4 stutters every 2 seconds, regardless of settings.  This is on marshmallow and nogout.

If reverting to lollipop fixes the issue completely, then what's changed between lollipop and marshmallow that could be the cause?

**Comment by cgutman** [comment]
@rzamoramty Remember that Android and PC are very different platforms. PC has more powerful hardware and often better wireless hardware, so it's not really apples to apples to compare what Steam does on a PC to what Moonlight does on a phone during times of subpar wireless performance.

That said, have you tested to see if it's any better with Moonlight v5.0.1 (without H.265 enabled)? The newer client uses Forward Error Correction and Reference Picture Invalidation (on recent Qualcomm chipsets) to reduce the effects of packet loss on streaming performance. But at the end of the day, if the packets just aren't making it, there's nothing any software solution can do about that.

**Comment by MrScruff300** [comment]
Hi all,

Just wanted to say that this is still an issue for me, even with the latest android version update. Just to be clear this is not a microstuttering issue, my moonlight on android runs super smooth for a good 5-10 minutes before the first major stutter which completely freezes video (although audio continues) it lasts 2-3 seconds and is then fine again for another minute or so before the same thing happens, this repeats itself. This used to work perfectly well until GFE was updated, I find it strange to believe it is dropped packages as it used to work perfectly well on the same device and network. Unless there is something in the update which has meant packages are more easily lost. Also I use moonlight on my raspberry pi which continues to work fine. I am on a very fast 5G wireless network.

Any ideas on what may be causing this?

Thanks!

**Comment by MrScruff300** [comment]
Also measured my nexus wifi speed at a solid 100Mbps down and 12 Mbps up, source of is a solid 200Mbps down and 12Mbps up so I doubt it is down to poor network or packets lost?

Just wanted to add, I absolutely love this app and thank you so much for your hard work. Being able to play my pc games remotely on my tablet is awesome!! Just wish I could get it back to smooth all the time rather than this infrequent major stuttering.

Cheers!

**Comment by MrScruff300** [comment]
Hi all,

Just wondering if we have a fix for this? It is still an issue for me, even with latest moonlight-embedded version and latest GFE version and drivers. It's strange it runs perfect for 10 minutes or so then I have a major stutter for 2-3 second which pixelates and freezes the screen, then it frees up and is bitter some for another 10 minutes or so, it seems a strangely consistent time frame between the major freezes. I have no micro stuttering at all. Is there a way to monitor moonlight to tell what is happening when I get the freezes? Still works perfectly on Raspberry Pi on same network.

Would really appreciate some help to get this working like it used to!

Many thanks in advance!
