### ISSUE TITLE
Cannot locate my PC on the network from the android app

### ISSUE THREAD

**Issue by ozonethegreat** [moonlight-stream/moonlight-android#377]
I have a router I've dedicated to game streaming. Its a dual band linksys router. Highest transmission rate is 54Mbps.

Im using a google pixel XL and an ASUS ROG gl551j. 

I have both devices on the same network and subnet with the same gateway.

I have tried using Remotr which worked pretty well on that setup. But I 'd prefer to use moonlight.

Geforce is started along with the streaming service process. 

And yet, moonlight on my phone is unable to find the PC

**Comment by Trasen** [comment]
Hey man,

Could you try connecting to moonlight with a different device? It's the best way to see if there's something wrong from the phone's end or if the problem is the actual gamestream.

I'm just assuming that you've tried to manually add the PC through it's local IP-adress, but i'm mentioning it if you've not.
