### ISSUE TITLE
PS4 Remote Play for Windows + Moonlight + DualShock 4 controller

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-android#411]
I tried to stream my PC with Moonlight which was streaming my PS4 with the official PS4 Remote Play for Windows. Streaming to the S7 edge was fine (_besides the micro stutters problem with Moonlight_). The problem is the DualShock 4 controller connected to the S7 edge is not recognized as a one, it will show up as a XInput device (because most games on PC with controller support need a XInput device to work, I know). Now what would be nice is if Moonlight had an option in the settings to use the DualShock 4 controller, well, as a DS4 controller and not emulating an Xbox controller. I unchecked "Xbox 360/One controller driver" but that didn't worked.

Since the unofficial PS4 Remote Play apps are not working since months, this would be the only option for people without an Xperia smartphone and for those who don't want to root (warranty, Samsung Pay etc).

**Comment by thw0rted** [comment]
I'm not a dev but multiple people have asked about this and I think the answer is that the Nvidia protocol has first class support for 360 pad emulation, because it's "for" the Shield, and the Shield is designed to replicate a 360 pad. That means "native" PS4 pad support just isn't going to happen, unless Nvidia supports using them on a Shield TV for example. You could ask about that on the Nvidia forums, maybe?

(Also, probably not what you had in mind, but buy a Vita! I've been using mine for Remote Play and I love it!)

**Comment by JasonS7notG5** [comment]
It could work in combination with the "VirtualHere" app which allows to connect USB devices on your smartphone and emulate as if it were connected on Windows. I think cgutman worked on something like this as a separate app which - I think - in theory could be implemented in Moonlight. This would also allow using Xbox, PS4 and other controllers on iOS devices! And even racing wheels or flight sticks!

**Comment by RiverCambria** [comment]
I found that using "Remote Play PC PREMIUM (Alpha)" worked and allowed key/button mapping. Not posting a link but you should be able to find by google.  Just a heads up though, when I did it there was too much latency. It didn't make things unplayable but if you are trying to be casually competitive on things like overwatch then its not be a good fit. It may be good for RPGs and the such.

**Comment by Sparko75** [comment]
Here for you https://www.youtube.com/watch?v=l0cDJbOUVoo&lc=z232xxyqnrvtzvdxx04t1aokgliwpsumuaywldlys4uvbk0h00410

**Comment by JasonS7notG5** [comment]
Looks like a solution but haven't tested it as of now. Somehow looks suspicious with copying files to the main Windows folder.

**Comment by Orof** [comment]
@Sparko75 This works! Now i can stream the PS4 Remoteplay using steam on moonlight, streaming it to my phone, and using a generic ipega controller. It works well with minimum lag 720p/60!

**Comment by CarpeDiemsNuts** [comment]
I've got this working amazingly well with the following setup..
Moonlight+GameVice+REM4P+PS4RemotePlay

GameVice - is super portable and uses the USB-C connection with headphone and AC pass-through to my Note 8 - Bought for its RAM/CPU and big WQHD amoled screen. I play anything I want @60fps on my home network or 1080P@60 over external WiFi/ 720p@60 over 4G (Make sure you drop to 720p maximum for 4G and/or have a massive data allowance as i burned through 25GB in month just on bus journeys to work playing Final Fantasy XV)

REM4P is a standalone remapping tool by Twisted who made Remote Play PC, its £12 for a lifetime licence, has continued support and works with any controller I've ever used, including racing wheels, pedals.
One of the coolest features of using this setup is, playing a game on my phone, then being able switch to the moonlight chrome plugin on my work pc, still using REM4P to continue any game with mouse and keyboard.
https://tmacdev.com/ is where you'll find REM4P along with a forum for support etc.

Funniest thing when my buddy started bringing his Nintendo Switch to work to play Zelda BOTW and i could plug my GameVice into my Note and drop into the same game running over CEMU with a higher resolution/enhanced shadows/lighting being played on a nicer screen. Then his jaw really dropped when i could switch to playing Destiny in HDR in 3 clicks on the same device.

Disclaimer: I should add that I have 1GB down/100Mbps up and have my PC/PS4 connected via CAT6 on a mesh wifi network at home, I'm lucky to live somewhere that has fibre to the home and work in an office with decent WiFi so that plus geography will always mean your experience may vary from mine but I hope this tip helps!

**Comment by gjc9620** [comment]
thx

**Comment by xXFr0z3nXx** [comment]
I installed everything and done everything but if i use moonlight the controller doesnt pop up on ds4 any help ?
