### ISSUE TITLE
Nvidia Shield 2017 model  4k microstuttering and no h.265

### ISSUE THREAD

**Issue by boostjunkie92** [moonlight-stream/moonlight-android#420]
Ive been having issues with moonlight and the new Shield.  no matter what bitrate i cap at i still get microstuttering constantly. ive tried 15-80mbps. anything over 50mbps and i get compression artifacts but going as low as 15 mbps with a noticeable image degrade i still get the microstutter. im streaming at 4k60fps.

also on the android settings if i force h.265 i get an error saying no h.265 encoder found. the shield definitely has h.265 encoding capabilities.

**Comment by cgutman** [comment]
Are your PC and Shield connected via Ethernet to your router?

The microstuttering issue is known and there is a build containing a workaround that may increase latency: https://github.com/moonlight-stream/moonlight-android/issues/349#issuecomment-307426527

Moonlight has blacklisted H.265 on Tegra X1 because it requires manual modification of the video bitstream to avoid triggering the decoder to buffer 16 frames (> 256 ms of latency). Moonlight doesn't do this yet.

**Comment by boostjunkie92** [comment]
yes, both the PC and Shield are hardwired with open ports with a gigabit connection. Nvidia gamestream averages a bitrate of 60-80mbps but if i attempt to go that high with moonlight the steam becomes unplayable. ill test out the build you suggested at different bitrates and see if that helps. thank you.

**Comment by cgutman** [comment]
Is there a reason that you aren't using Shield Hub to stream on your device?

**Comment by boostjunkie92** [comment]
theres an issue with the gtx 1080ti and shield streaming which causes grey artifacts resembling a bad memory overclock to generate along the bottom half of the stream i also get intermittent compression artifacts as well.  Nvidia has not address the 1080ti issue

**Comment by boostjunkie92** [comment]
ya when i enable that i end up getting high packet loss errors and very bad compression artifacts  quite often and thats with a 30mbps cap even

**Comment by cgutman** [comment]
Hmm, as far as I understand, that option simply disables H.265 encoding support. Since Moonlight also has no H.265 support, it looks like the same thing happens to Shield Hub when it can't use H.265. The packet loss rate skyrockets after a certain bitrate is exceeded. Since H.265 is a much better compression codec than H.264, it's likely that the bitrate needed to cause H.265 to have the same effect is higher than your selected bitrate.

One thing you may try is going into Device Manager on your PC, right-clicking on your Ethernet adapter, going into Properties, and changing the Speed to "100 Mbps Full Duplex". Other users have had some success with similar issues by doing that - https://github.com/irtimmer/moonlight-embedded/issues/164#issuecomment-141414002

**Comment by boostjunkie92** [comment]
that makes sense. im kind of stuck in the middle i guess.  the microstutter issue was reduced in the build you pointed me to if i set my bitrate to about 30mbps but the image suffers.  I tried the ethernet workaround before but didnt see any improvement, ill try it again while enabling OC and see if that helps

**Comment by boostjunkie92** [comment]
so setting my speed to 100/full corrected the loss issue. 0 lost packets in 15 minutes, went back to moonlight and i was able to set my bitrate up to 100mbps but caused stuttering, the sweet spot is about 70mbps.  tried to manually set the card to 1000/full but that caused issues again, something to do with having 1000mbps overhead is a problem on both platforms

**Comment by Wylhelm** [comment]
I have all the symptoms mentionned in this post but on gamestream. I have compression artefacts along the bottom half of the screen and shuttering. 1080p and 4k. I have a 1080ti. Setting up network adapter to 100/full helped a bit but still... I ended up using moonlight instead. With it there is a bit of microshuttering but it's barely noticeable in Witcher 3. In Gta V, i can see the traffic is not fluid. H.265 is enabled. Tried to change the bitrate, symptoms are still present. Bought Shield to replace Steam Link to stream in 4k. Steam link is fluid period it just work, I never had any issues nor had to change settings on my pc or the unit. Will stick with it for long gameplay sessions.
