### ISSUE TITLE
Audio Playback Device

### ISSUE THREAD

**Issue by Bexa2** [moonlight-stream/moonlight-android#449]
Everytime I connect to PC via Moonlight one of those appears, good.

But when I disconnect the Audio Playback Device doesn't dissapear or switch to the previous one.

Is there something you can do or do I just have to disable it (It doesn't let me switch either, it switches back to the device created so I have to disable it)

![audiopdevice](https://user-images.githubusercontent.com/32035811/31036047-d74fe8d8-a56a-11e7-9abe-4d97d9a04624.PNG)

Wait, maybe this is something related to NVIDIA's GameStream? I'll submit this just in case.

**Comment by Cur** [comment]
This also happens with me but it stops cloning at 4.

When i turn on my PC and log into windows however it will continually do the new connected device ding an increasing number of times matching times i use moonlight - finish then close it.

Probably being caused by the fact i need to disable the audio device because it's hit and miss with after disconnecting whether it will return the audio to my sound card or keep it on the moonlight one as when i right click and set as default my main sound device it does nothing so i literally have no choice to get sound back without restarting.

Windows 7
Sound Blaster Z
Moonlight (non rooted) for Android running on 6.0

**Comment by cgutman** [comment]
Are you quitting using the Moonlight app's "Quit Streaming" button, quitting the game from the streaming itself, or just closing the Moonlight app and leaving the stream running?

**Comment by Cur** [comment]
That would probably be it.  Where is the quit stream button sorry?  i have not seen anything like that that stands out.

**Comment by cgutman** [comment]
When you hit the back button to stop streaming without closing the app or game on the host PC, Moonlight will mark that game with the Play button in the app grid that indicates the game is currently active on the host PC. When you tap on that game, it will give you the option to resume or quit.

This is assuming you're not quitting the game from within the stream itself (which will also cause the stream to end).

**Comment by Bexa2** [comment]
@cgutman 

You are right, thank you.
I always closed the app itself, not the session.

**Comment by Cur** [comment]
This fixed it for me.  thanks heaps ! Any idea how to fix it going ding for new hardware every boot 50 times?
