### ISSUE TITLE
Destiny 2 ignores virtual controller

### ISSUE THREAD

**Issue by ghgshellshock** [moonlight-stream/moonlight-android#471]
I added the Blizzard App to GeForce Experience. Overwatch accepts the controller inputs while Destiny 2 ignores them.  Would this be an issue that Nvidia or Bungie would need to address?  Also, would creating a virtual game controller driver in windows that moonlight could send commands to be a good workaround for games that don't support the Moonlight controller inputs?

**Comment by cgutman** [comment]
Nvidia or Bungie could probably fix this. I'd expect Nvidia is most likely to find a workaround in the next GeForce Experience release, since Destiny 2 is a very popular game.

There's a forum thread about Destiny 2 issues: https://forums.geforce.com/default/topic/1027249/gamestream/destiny-2-not-visible-or-playable-via-gamestream/1/

**Comment by cgutman** [comment]
Fixed in GeForce Experience 3.11. You can access it in beta by checking the Experimental Features checkbox in GFE settings or wait for it to reach the production release.
