### ISSUE TITLE
Black screen only can see GFE window

### ISSUE THREAD

**Issue by Sagasev** [moonlight-stream/moonlight-android#477]
I just got a new laptop, gigabyte aero14, with gtx1060 and wanted to try moonlight.
It didn't work, it would connect but the video is black without sound. But the touchscreen mouse works tho.
I thought it was because of the new version of GFE 3.11.0, I tried downgrading to 3.10 and installing last release of the .apk but same problem.
I can see only the geforce experience window on the phone, but nothing else, all black. Very strange.

Any ideas?

Many thanks.

**Comment by cgutman** [comment]
What are you attempting to stream? A game or your desktop? If a game, which game?

**Comment by Sagasev** [comment]
Hi there :)
I tried streaming Doom 4, desktop, etc. I always have the same problem.

**Comment by Sagasev** [comment]
I tried setting up the gtx1060 as default main card (so it doesn't switch to the integrated graphics) without luck.
My phone Samsung Galaxy A5 (2017) works with Moonlight as I used it a lot with my old computer (gtx 970).
My settings are:
i7 7770hq
nvidia drivers 388.31
geforce experience 3.10.0.95 (also tried with the last version 3.11)
The strange thing is that I recieve sound and I can control the mouse with the phone. The screen is black but if I open Geforce Experience, I can only see that window on the phone.

**Comment by cgutman** [comment]
I wonder if it's somehow related to Optimus. Can you try setting your machine to always use the discrete GPU in the Nvidia Control Panel and see if that makes a difference?

**Comment by Sagasev** [comment]
Hi,
Yes I tried always using gtx1060 as default graphic card from the nvidia panel but still same problem. :( any ideas?

**Comment by Sammyhusky** [comment]
I'm having an identical problem except I'm using a Razer Blade (synapse is disabled) and a PS Vita as my device. I can see either the GFE screen or a black screen, inputs and sound are working great. Tested with Binding of Isaac, Steam, Divinity 2

**Comment by Sagasev** [comment]
Hopefully they will update this. I still can't make it work. :(

**Comment by Sammyhusky** [comment]
If I launch streaming without geforce experience open I can play games in windowed mode, though the lag is harsh. Might be an artifact of my version.. Hope this helps you.

**Comment by cgutman** [comment]
Any change with the 390 drivers and GFE 3.12?

**Comment by thw0rted** [comment]
@Sammyhusky is the Vita version officially supported? This is the issue tracker for the Android build.  (I have a Vita but am trying to avoid the hassle of homebrew -- would *kill* for Moonlight in the PS Store...)

**Comment by Sammyhusky** [comment]
@thw0rted I know it is, I just thought my information might be helpful since it seems to be on the PC side and the Vita version uses the android version as a base. I'm not expecting any help from here just to contribute a little info. I don't believe it's officially supported but I've seen people have great success with it, but you need to be softmodded with henkaku for it to work AFAIK there isn't a way to do it on 3.61+

**Comment by thw0rted** [comment]
Ironically, I have two vitas but I've set one of them up for the kids.  Hmm, I could probably get a third for around a hundred bucks.... :D

But now we're getting off-topic.  Do you know if the Vita version has a public tracker (github or otherwise)?  I assumed that while actually hacking the device enters into a legal gray area, just maintaining an application should be OK to do out in the open...

**Comment by cgutman** [comment]
The Vita port is on GitHub here: https://github.com/xyzz/vita-moonlight
