### ISSUE TITLE
High decode latency on honor 9

### ISSUE THREAD

**Issue by ChevalFugace** [moonlight-stream/moonlight-android#479]
Phone: honor 9 (stf-l09C432B150)
Android: 7.0 emui 5.1
moonlight: 5.5
GFE: 3.11.0.73

Moonlight shows an average decode latency of 47ms on h264, same on h265; which is abnormlly high for this device compared to the honor 8 which shows a decode latency of 6ms.
I've tried streaming with the b130 firmware but still 47ms.

I have also noticed that the back button does not work while streaming. 

Does anybody have the same issue on this device?

**Comment by georgeleo** [comment]
Well not on that device I'm using the Mate 10 and have the same issue with the decode Latency, playing a game is imposible constant lag and disconnect, I used to have a Moto X play and that worked great, I bouth the Mate 10 because the mhl Port to play games on tv when I'm out, but for the time being that is imposible for now.
