### ISSUE TITLE
Connection Terminated

### ISSUE THREAD

**Issue by hunterkorvis** [moonlight-stream/moonlight-android#505]
I have a new Shield TV and have been having issues getting Gamestream to work. I have gone through Nvidia Support and nothing we have tried as worked. I haven't listed every troubleshooting step I took because I've honestly forgotten everything I have tried (I have been dealing with this for weeks), but basically all of the common suggestions short of completely re-installing my OS. I received some suggestions (not from Nvidia) to use Moonlight instead. However, I receive a "connection terminated" error shortly after a connection has been established (I get a second of audio but no video). This happens both via the Shield TV as well as using my android phone. In case it is helpful, the error code I get on the Gamestream side is Error 800e9408 - Lost connection to server.

I am guessing the issues are both related but since no one at Nvidia was able to help me, I figured I should check with people here. Their current theory is that it is my router and they want me to try testing with another one (which I don't currently have access to). FWIW I am using a Netgear r6700 which is listed as a supported router.

I have installed/re-installed GFE several times and even tried using older versions, all versions have the same issue. Finding my PC and connecting to it occurs without issue. I would be happy to provide any logs that may be needed but here are some basic specs:

Windows 10 64bit Pro version 1709
GFE and Nvidia drivers all on latest versions
Intel i7-6700k
Nvidia GTX 1080
Netgear r6700
PC and Shield TV are on ethernet

**Comment by Trasen** [comment]
Hello there,
Can you install Moonlight on your phone and try to use Gamestream though that device instead?

Safe way to rule out issues with the Shield itself.

I would also suggest running DDU to rule out issues with the drivers : http://www.guru3d.com/files-details/display-driver-uninstaller-download.html, run the tool and let it reboot to safe-mode in Windows, remove all Nvidia drivers. Reboot and reinstall the latest drivers, retry Gamestream with the Shield.

If nothing of this works: issue is coming from the router, look for UPNP settings and enable them. If it doesn't have UPNP support, open ports (google which ports to open for Gamestream).

**Comment by hunterkorvis** [comment]
I went through your steps with no changes. Opening ports should not be necessary for the wired devices (PC/ShieldTV) but I have had them open anyways since I have been testing via Moonlight on my phone as well. You can verify those settings here:

https://i.imgur.com/wxqiaVH.png

**Comment by Trasen** [comment]
That's unfortunate - since the driver is re-installed after running DDU we can assume that the driver isn't part of the issue. Reason we do this is because of the possibility of cross contamination between Nvidia drivers after multiple driver updates.

I saw your message on the nvidia support forum, and since they are recommending trying a different router i would suggest the same. One could argue that you should do a factory reset of your Netgear router and try running in on default settings to see if there's any change, but there's no garauntees.

However, this might also be a service issue on your computer not related to Nvidia. Antivirus software, firewall, something hogging the ports Gamestream want's to use et.c.

Personally i would refrain from trying to run Moonlight on Shield since the Gamestream compatability, connection wise, is better because of the UPNP certificate from Nvidia.

**Comment by ronferri** [comment]
Hi Hunterkovis,

Please have a look here: https://github.com/moonlight-stream/moonlight-pc/issues/288

Switching to 2.4GHz network instead of 5GHz fixed it for me but running at poor quality.

**Comment by hunterkorvis** [comment]
Thanks but I don't think that is the issue, at least, Gamestream does not even work on a wired connection. I tried a new router (Rt-AC88U) and I have the same issues. This leads me to think there is an issue with windows10/other software conflicts. I have tried disabling all other programs but can't get it to work so I may need to re-install windows.
