### ISSUE TITLE
Failed to start input connection

### ISSUE THREAD

**Issue by jo3stevens** [moonlight-stream/moonlight-android#51]
I get this error every time I try and start a game. I can see the video working behind the notifications, then I get this error and it goes back to the game menu. I turned off my firewall to see if it was a port issue but still not working. I've also tried on my home and work network and the errors happens on both.

**Comment by cromatic99** [comment]
I have the same error, can add the following:

- have to pc with roughly the same cards+config [win7 core i5 2500k Gerforce 780 each  with a xbox360 controller]
- happens on only one of them [both PC in the same lan]
- the non working stream PC worked for a time but stopped [cant remember that I did any kind of upgrade]. The only thing I can remember is plugging in an out an additional joystick].

- to run limelight I have 2 device [ a nexus 5 and a galaxy note 10.1 (2014)] both show this error on the problematic PC.

based on the above this seems related to the server but since I don't know were to look for logs that's all I can do.

**Comment by cgutman** [comment]
Re-open if this is still an issue.
