### ISSUE TITLE
You may want to look at GeForce NOW / the future

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-android#515]
First I want to thank you for your work on Moonlight, I personally had a rough time with the micro stutters but thanks to the community the micro stutters are gone with the 59 FPS trick. I hope that gets build into the main build.

GeForce NOW takes it to the next step with letting the game running with 120 FPS on the Host PC and streaming it to the client with 60 FPS. This reduces latency even more apparently. They also have dynamic bitrate streaming so users without stable internet connection dont get any lags. It also works on many PCs with Intel HD 2000+ IGPUs. Maybe you can add stuff like that to the Android and Chrome clients at some point. Thanks for reading.

**Comment by JasonS7notG5** [comment]
Also an integration with your [USB/IP Server](https://play.google.com/store/apps/details?id=org.cgutman.usbipserverforandroid&hl=de) into Moonlight so we can use the steam controller, racing wheels, flight sticks etc.

And streaming with over 60 FPS, phones like the one from Razer have 120Hz now. HEVC supports up to 1080p 300fps, 2160p also with 300fps and even 4320p with over 120fps.

Well thats the dream / the future.

**Comment by JasonS7notG5** [comment]
And the Chrome addon supporting HEVC and HDR.

**Comment by muffinmannameistaken** [comment]
I did get a invite to Geforce now and I have been testing it the pass few days, I really can't say much about latency because i live in Alaska everything  is a bit laggy,  but I did notice that all there games that they have to offer you must own them first before you can stream them, I thought this was kinda pointless because you can just stream them with Steam.

**Comment by thw0rted** [comment]
@muffinmannameistaken the point of the NOW service is that you don't need to own a high end gaming system at all, it's for people who just have a Chromebook or Macbook or something like that.  They have a similar service (with the same name, which is dumb) that streams to the Shield tablet and set-top box, for much the same reason.

**Comment by Niglb** [comment]
Agreed - I have a decent home PC (geforce 1060, 16gb ram, AMD fx 8 core CPU, SSD) and geforce now offers a better streaming experience then my pc to TV machine with moonlight right now. 

I would love to see moonlight support.

**Comment by cgutman** [comment]
I think this is getting a bit off-topic. The initial ask was about investigating NVIDIA's optimizations in GeForce Now. There wasn't anything about supporting connecting to GeForce Now.

For a while now, including during the Grid Beta, I've drawn the line at communicating directly to Nvidia's own hosted GameStream servers. IMHO, that's going too far, since we may be incurring costs on their end, affecting the reliability of their servers due to Moonlight bugs, etc.

Moonlight will never connect to any Nvidia-hosted GameStream server without explicit permission from Nvidia to do so.

**Comment by Niglb** [comment]
Fair position, completely respected - as I'm in the beta it's hard not to get excited about geforce now, and I use moonlight so much, I'm very greatful for the project.
