### ISSUE TITLE
Cgutman, would you please respond...

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-android#521]
https://github.com/moonlight-stream/moonlight-android/issues/349

**Comment by cgutman** [comment]
Please avoid filing new issues to try to attract my attention. That behavior would result in an immediate ban for spamming in most FOSS projects. I understand why you do it, but realize I also have responsibilities outside of Moonlight, like my real job that pays the bills.

We're all getting closer to the solution for the microstuttering issue, in part thanks to you and others on that issue. As always for tricky problems like these, it takes time to come to a breakthrough idea that makes progress. I've already tried many frame pacing ideas that didn't work, but nobody usually sees those since they don't leave my machine.
