### ISSUE TITLE
RTSP handshake fail

### ISSUE THREAD

**Issue by AdriftUrchin** [moonlight-stream/moonlight-android#528]
So the streaming on local works just fine, but when I stream over internet I get that error. It used to work just fine a week or so ago but ever since I tried to use it again it doesn't work. Before I started trying to stream again, I accidentally installed Avast antivirus but deleted that (don't know if that could've caused something to happen). I also got malwarebytes premium trial but that has ended (again I don't know if that could've caused something). I have all the ports forwarded correctly (as seen in the picture below) and I've tested them with the port tester and they are open. I've noticed when I try to open something over the internet that is able to open the application, so some connection is being made. Any help is appreciated as I have been trying to solve this for quite some time now.
![chrome_2018-02-08_00-50-24](https://user-images.githubusercontent.com/1494697/35957657-bbe27c66-0c6a-11e8-9595-01d5a00fb2c4.png)

**Comment by nathankferguson** [comment]
Having the exact same issue.  Haven't used Moonlight in a while on my mobile, went in to set all my ports from the guide and RTSP handshake keeps failing.  Tried every possible TCP/UDP 48010 port combination that I've seen in different threads, and no help.

**Comment by Slayer418** [comment]
Don't know if you guys are trying to stream on mobile internet or on a WIFI connection (over the internet still) but either way, I heard some mobile service provider (scumbag ones) can block RTSP request, just like a work office can be behind a proxy that does just the same.

**Comment by JoeJoeyMa** [comment]
Do you try to confirm that it is a moblie phone instead of a computer that has a problem with the connection? I also having the exact same issue too, but it was visit a LAN computer normally, it was finally found to be a computer.

Make sure Win10 NvContainerNetworkService-NVIDIA NetworkService Container-
"C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe" 
is open

**Comment by nathankferguson** [comment]
I can connect over my WiFi no problem, it is just the mobile network that is failing.  Didn't think about carrier support as an issue, but could be.  I have Cricket Wireless, but I'm fairly certain I was using them last time Moonlight was working.

**Comment by AdriftUrchin** [comment]
I have two phones, both different mobile networks neither work. I also tried using my schools wifi to no avail.

**Comment by MagFlux** [comment]
@GManASG,

Thanks for the information, really unfortunate but sounds like it's the service provider causing these issues this based on that. Used to work for me as well and I can no longer connect via cellular on AT&T.  It been a while since I tried to stream via my cellular connection, so I can't pinpoint when it stopped working. Like others I can connect and launch applications but the RTSP ultimately fails. Everything works via Wi-Fi just fine.

**Comment by MagFlux** [comment]
Well, I'd like to add that I just attempted using a demo RTSP stream provided by Wowza media systems and it works for me via Wi-Fi (Comcast) as well as via cellular (AT&T). Not sure what to make of that information but figured I'd provide it. I used the VLC app on Android Oreo 8.1.0 to open said stream.

[rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov](url)

**Comment by cgutman** [comment]
I wonder if the issue is connecting RTSP at the non-standard 48010 port number that GeForce Experience uses. Can you try running a Wireshark packet capture on your PC while you try to stream over LTE, then save the capture and post a link here?

**Comment by AdriftUrchin** [comment]
@cgutman  Don't know if you asking me, if so sorry for late reply. Anyways I don't know how to do what you said.

**Comment by MagFlux** [comment]
@AdriftUrchin,
Wireshark is a FOSS network packet analyzer utility. I use it quite often for work and have no problem doing it but I just haven't had the chance to do so. That being said if you want to try before I get around to it, check out https://www.wireshark.org/ to download the utility. Since @cgutman isn't asking for you to do any of the analysis, all you need to do is install it, start the capture, attempt to recreate the problem, and then send him the capture file so he can analyze it and see what may be going on.

**Comment by Meems33** [comment]
Similar to #609, #612. It seems the fix put in to 2.4.5 did not fix it.

It also happens over LAN. GFE 3.13.1.30 moonlight-embedded 2.4.6 on debian pi 3. All relevant ports should be open.

Wireshark packet capture: 
Incoming from pi UDP 48010 52 data bytes:

> 0000   8f ff 14 1e 82 ff 00 01 00 00 ff ff 00 00 05 78
> 0010   00 01 00 00 00 00 00 01 00 00 00 00 00 00 00 00
> 0020   00 00 13 88 00 00 00 02 00 00 00 02 52 5c ab 1e
> 0030   00 00 00 00

PC does not send back any data. It does however enter big screen mode in steam. 

@cgutman

**Comment by cgutman** [comment]
@Meems33 Can you paste the XML output of http://localhost:47989/serverinfo on your PC?

**Comment by Meems33** [comment]
Per https://github.com/irtimmer/moonlight-embedded/commit/df0114ee051822c580ff45ba3a997e61771b791a it requires updating moonlight-common. I would assume that the same fix would be needed for android as well.

http://localhost:47989/serverinfo:
`<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>0</CurrentClient><GfeVersion>3.13.1.30</GfeVersion><GsVersion>gs_04_05_23698325</GsVersion><HttpsPort>47984</HttpsPort><LocalIP>127.0.0.1</LocalIP><LocalIPs><Address>192.168.0.112</Address></LocalIPs><LoginState>2</LoginState><MaxLumaPixelsH264>737235008</MaxLumaPixelsH264><MaxLumaPixelsHEVC>589622848</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>0</PairStatus><ServerCapability>1847</ServerCapability><ServerCodecModeSupport>3843</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>60</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>60</RefreshRate><Width>1280</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId>*****</accountId><appversion>7.1.405.0</appversion><currentgame>999999</currentgame><gamelistid>f580c7e534224318530e44256d2ec5d5</gamelistid><gputype>GeForce GTX 1060 6GB</gputype><hostname>DESKTOP-SAOGNKN</hostname><mac>00:00:00:00:00:00</mac><numofapps>0</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_BUSY</state><uniqueid>57a0ace9-e4d9-4262-9e7d-136b861778f6</uniqueid></root>`

**Comment by cgutman** [comment]
@Meems33 It looks like your serverinfo is as expected. Current moonlight-common-c will detect your RTSP protocol properly, as will current Moonlight clients.

The issue here actually relates to RTSP traffic being filtered by a firewall after the move to TCP in GFE 3.12, not sending over UDP instead of TCP as was happening in your case.

**Comment by AdriftUrchin** [comment]
Sorry for ditching this post, the phone that I used to stream kinda soft bricked on me. I'm gonna be going to get a new phone in a few days here so if the problem still arises I would like to revive this post.

**Comment by MagFlux** [comment]
I guess this isn't too common of a usage scenario but I can confirm that it's still a problem for me on AT&T. Just revisiting since this issue was recently marked as stale by the bot.

**Comment by AdriftUrchin** [comment]
Just started school again and got a new phone. When i get back home I will see if I still have the same problems.

**Comment by GManASG** [comment]
Definitely still have this issue

**Comment by AdriftUrchin** [comment]
I should also note that when i do use moonlight i use it over wifi (not local as im at school duh :P) but when im at home i test it over a mobile connection to make sure everything works.

**Comment by redlinejoes** [comment]
If you're in your WiFi at school and not cellular then it's possible they
are blocking the ports. You need to use it the same way you are testing it.
That is from cell not WiFi networks

Cheers,
Joe

**Comment by AdriftUrchin** [comment]
Just tested it on my mobile connection and it works but i have to have my firewall turned off.

**Comment by redlinejoes** [comment]
If a FW is blocking ports then you will have to disable the FW or a better
solution is to simply open the required ports and not disable the FW
entirely. All the required ports are documented.

Cheers,
Joe

**Comment by AdriftUrchin** [comment]
Ok this is odd came back home enabled my FW then disabled it again to check if it still worked and im getting rtsp handshake fail yet again wtf lmao.

**Comment by cgutman** [comment]
Please try again with v5.10.3

**Comment by MagFlux** [comment]
@cgutman I can confirm it now works via AT&T. Nice work, thanks for the update!

**Comment by donkeyhigh** [comment]
I'm having a similar issue. Errorcode 10035. It's weird, because it works with 2 of my laptops on wifi and wired connections, and on my android over both wifi and cellular 4g. But my third laptop gets the error, even though it's connected with cable or wifi to the same local network. So I'm guessing it has something to do with this laptop in particular. I went to the windows run thingy and wrote firewall.cpl, added moonlight to my windows firewall whitelist, but still won't connect. Any ideas what it could be? The ports are forwarded correctly, or else it wouldn't have connected over cellular, so I'm kind of confused..
