### ISSUE TITLE
Is there a list of keys that dont work in android?

### ISSUE THREAD

**Issue by SESNut** [moonlight-stream/moonlight-android#553]
Like the windows key and media keys and alt, etc

**Comment by samgalactic2** [comment]
From what I can tell the physical keyboard is interpreted as an android keyboard (not a pc keyboard), so pressing escape is interpreted as 'back', pressing alt+tab switches the phone windows. Any non-android button on a physical keyboard won't work, but there are android apps that let you alter the layout of you physical keyboard so that you can change what a specific button press does (but this is limited to the Android inputs, so not that helpful).
