### ISSUE TITLE
[Feature Request] Pass on no controllers at all/Use controllers connected to computer.

### ISSUE THREAD

**Issue by vatomalo** [moonlight-stream/moonlight-android#616]
I use Moonlight-android on my Android TV and Moonlight-Vita on my PSVita.
Therefore, I cannot rename rxinput.dll and etc so that it no longer uses the Moonlight controllers on my Android tv(Input on my Vita would not work on the go), althought it does have Bluetooth, I cannot connect controllers to it as its a dumbed down Bluetooth system, also would need root for DS3 and DS4 controllers. And it would be too much of a hassle to pair them each and every time. 

Would you guys please make a feature that disables the controller passthrough from the system and does not create a "player 1" controller? 
I hope it's not too much to ask for this is basically my go-to application, and the number one homebrew I want to be ported for any system, thank you guys so much for your efforts =)

My humble appreciation 
Thank you.

**Comment by thw0rted** [comment]
I don't think this is possible.  The reason the FAQ says to rename the DLL is because the GameStream server side is set up to emulate a controller when a client connects -- that's just how it works, and renaming the DLL interrupts this process on the server side.  The GameStream protocol doesn't provide a way for clients to say "I don't want to be a controller", so there's nothing for Moonlight to do about it.

If I were in your situation, I'd probably make a batch file on my desktop that moves the DLL, pauses, then moves it back -- that way, when you want to connect with your Android TV (and use a controller that's directly connected to your PC, I guess?)  you can run the BAT (perhaps connecting to your PC via TeamViewer?), then while it's at the `pause` command, run Moonlight there and play.  Then, you can connect back to the PC, let the script finish, and it's ready to play from your Vita.

Would it maybe be more straightforward to pair a controller you like to your Android TV?  How's DS4 support there?  Can you pair a Steam Controller via Bluetooth with the new firmware update?

**Comment by vatomalo** [comment]
@thw0rted No I'm sorry my TV only supports AD2P devices for some reason unexplained to me.
I really wish there was another way to solve this. Such as setting moonlight controller to a much higher number than controller 1, like maybe controller number 10. What you explained with the batch files is very doable, but it is much more of a hassle than what I would like it to be :(


Thank you so much for your help anyways and I will look into a way to solve this 👍

**Comment by cgutman** [comment]
If you're on GeForce Experience 3.14.1, this should work now.

**Comment by isilkin** [comment]
Which DLL do I need to rename on my computer and where is it located. I think I can totally create an autohotkey script to deal with this issue. I agree with the original poster that this should be a simple checkbox feature.

**Comment by cgutman** [comment]
This already works with the latest GFE. If you don't plug any gamepads into your client, it won't virtualize any either.
