### ISSUE TITLE
Remote WOL issue

### ISSUE THREAD

**Issue by kurac338** [moonlight-stream/moonlight-android#631]
Hi, I have added my PC through the app, with both a LAN address and through WAN.
They appear as one computer in moonlight, and if I view the PC details, the remote address is the same as local (private address).
Even though I can stream through both LAN and WAN. The issue is that WOL requests only work on LAN.
I have tested this by sending a WOL request through WAN from my laptop and it worked, so the issue seems to be Moonlight related. Is it possible that it somehow incorrectly maps the local and remote addresses for WOL?

If there is any other information needed, I will gladly provide it.

**Comment by rogeriskira** [comment]
I have been trying to resolve that issue but in the end I found no solution. So to rectify that limitation I created a VPN server through my router and I simply turn on the VPN to use WOL away from home.

**Comment by ElSturge** [comment]
I too am having this problem. When the PC is switched on, I can stream to my phone with either WiFi or 4G. When the PC is switched off or in sleep mode, i can only turn it on or wake it if i send a signal whilst connected to the same network. Using 4G doesn't turn it on. I used to have it working perfectly but then my PC had a fresh Windows install so I've had to set it up again, and i cant think of anything I've missed in terms of setting it up. I've used the .msi tool and it didn't help, I've tried setting the ports manually and still nothing. It just won't wake up from sleep when I'm using 4G.

I have also tested it on multiple phones with the same results. I thought it may have been because of a new phone. 

Any help would be appreciated because I'm really out of ideas and I mainly use moonlight whilst away from home.

**Comment by rogeriskira** [comment]
Your best bet is to use OpenVPN on your phone so you can wake your computers always.

**Comment by cgutman** [comment]
OpenVPN won't help here. The PC is off, so it will be disconnected from the VPN tunnel.

The problem here is a fundamental property of how TCP/IP networks work. They depend on a PC responding to ARP packets in order to allow any traffic directed at that host specifically (unicast) to be delivered. Without a PC that can respond to such requests while sleeping or an enterprise router with IP-directed broadcast support, it's impossible to wake a PC from a different network. Wake-on-LAN packets are usually broadcast packets to avoid this issue, which means they're sent to the whole network using the special address 255.255.255.255 which avoids ARP but can't pass through routers.

The only way to support remote WoL using consumer routers is by having a device/PC which is always on act as a WoL-proxy and retransmit the directed WoL packets it receives back onto the network as broadcast packets. There are programs that do this (none of which I've tried): http://www.mylanviewer.com/wake-on-lan-proxy-server.html
https://www.green-it-software.com/pdf/Raspberry%20Pi%20as%20WolProxy%201.0.3.pdf
https://github.com/kfix/SleepProxyServer

Or the easiest option, just don't let your PC go to sleep :)

**Comment by ElSturge** [comment]
Damn, that's a shame. I used to be able to wake it up no problem wherever I was through the moonlight app. Could be my routes firmware that's updated possibly?

**Comment by vladone97** [comment]
Did you add your computer's mac address and ip address to the router's ARP table? I used to have this problem too and this turned out to be the cause.

**Comment by ElSturge** [comment]
It's okay, I managed to resolve the problem. Was a setting in my computer I
thought I'd changed

**Comment by kurac338** [comment]
Problem resolved by adding static ARP entry for the my servers MAC.
