### ISSUE TITLE
Unable to Pair. Prompt on PC closes instantly

### ISSUE THREAD

**Issue by ripps818** [moonlight-stream/moonlight-android#702]
I'm unable to use my Windows 10 PC to any android device with moonlight, because when I try to initiate a pairing, the prompt on the PC appears and disappears in a fraction of a second. I'm not sure how to complete pairing if I'm unable to to actually authenticate usage.

**Comment by cgutman** [comment]
For troubleshooting, you should ask for help on our Discord server since this seems like an issue with Nvidia's software. More people can help you there.

There's also a bunch of troubleshooting steps here: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#unable-to-stream-at-all-on-the-same-network-as-the-pc
