### ISSUE TITLE
suggestions:Can you add a virtual keyboard?

### ISSUE THREAD

**Issue by BlessWz** [moonlight-stream/moonlight-android#762]
Sometimes I need a virtual keyboard, I can only quit moonlight and use teamviewer

**Comment by thw0rted** [comment]
From [the documentation](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#keyboardmousegamepad-input-Options):

> Tap with three fingers to open the on-screen keyboard (Android and iOS only).

Does this solve the issue?

**Comment by BlessWz** [comment]
> From [the documentation](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#keyboardmousegamepad-input-Options):
> 
> > Tap with three fingers to open the on-screen keyboard (Android and iOS only).
> 
> Does this solve the issue?

thank you.This solves the problem, but how to turn on the keyboard on the TV? And I still have a question, how can I simulate a mouse with touch?

**Comment by thw0rted** [comment]
From the same page I linked above:

> If you don't have a mouse connected to your Android device, you can emulate one using a game controller. Press and hold the Start button to toggle mouse emulation. When mouse emulation is on, you can use either analog stick to move the cursor. The A button left clicks and the B button right clicks.

I'm not sure what you mean about a keyboard on TV -- are you using Moonlight on both Android and a Fire TV or NVidia Shield?

**Comment by BlessWz** [comment]
> From the same page I linked above:
> 
> > If you don't have a mouse connected to your Android device, you can emulate one using a game controller. Press and hold the Start button to toggle mouse emulation. When mouse emulation is on, you can use either analog stick to move the cursor. The A button left clicks and the B button right clicks.
> 
> I'm not sure what you mean about a keyboard on TV -- are you using Moonlight on both Android and a Fire TV or NVidia Shield?

I use moonlight on Android TV.I want to turn on the virtual keyboard on moonlight for Android TV like a mobile phone touches the screen with three fingers.Besidess, do you considered providing full keyboard support like rd client? (With win, ctrl, alt)

**Comment by thw0rted** [comment]
I'm just a user like you, not a developer, FYI.  It sounds like you have two separate suggestions: one, add a controller command for opening the virtual keyboard, at least when running on a device without a touchscreen; two, add an additional virtual-keyboard for keys that are needed on a PC but not on a phone / set-top box.  You might want to edit your original post (and maybe title?) to reflect these additional details.

Suggestion one is probably pretty straightforward and I suspect @cgutman wouldn't mind doing it.  If "Hold Start" is bound to toggling mouse mode, it would probably make sense to bind a long-press of Select / Share / Back to pop up the virtual keyboard.

Suggestion two is a much bigger effort, especially if the "keyboard" needs to work across multiple types of devices (touch / TV).  I like the way Teamviewer handles it, with a separate "show special keyboard" button that only has PC keys like win/ctrl/alt, shift, the function keys, PgUp/PgDn/Home/End, etc etc., but adding something like that is probably a lot of work.  As a workaround, once suggestion #1 is implemented you could always look for a "special keys" virtual keyboard on your device's app store.  I used to use the "Hacker's Keyboard" a lot because it had keys for e.g. Escape, Tab, etc, and was useful when running a terminal emulator on the phone.  You could also run your remote application through Steam, then use the universal input remapping feature to bind controller buttons to special keys or combinations thereof.

**Comment by BlessWz** [comment]
> I'm just a user like you, not a developer, FYI. It sounds like you have two separate suggestions: one, add a controller command for opening the virtual keyboard, at least when running on a device without a touchscreen; two, add an additional virtual-keyboard for keys that are needed on a PC but not on a phone / set-top box. You might want to edit your original post (and maybe title?) to reflect these additional details.
> 
> Suggestion one is probably pretty straightforward and I suspect @cgutman wouldn't mind doing it. If "Hold Start" is bound to toggling mouse mode, it would probably make sense to bind a long-press of Select / Share / Back to pop up the virtual keyboard.
> 
> Suggestion two is a much bigger effort, especially if the "keyboard" needs to work across multiple types of devices (touch / TV). I like the way Teamviewer handles it, with a separate "show special keyboard" button that only has PC keys like win/ctrl/alt, shift, the function keys, PgUp/PgDn/Home/End, etc etc., but adding something like that is probably a lot of work. As a workaround, once suggestion #1 is implemented you could always look for a "special keys" virtual keyboard on your device's app store. I used to use the "Hacker's Keyboard" a lot because it had keys for e.g. Escape, Tab, etc, and was useful when running a terminal emulator on the phone. You could also run your remote application through Steam, then use the universal input remapping feature to bind controller buttons to special keys or combinations thereof.

In fact, I have another suggestion, hope that the mouse touch of moonlight can simulate the mouse with fingers like rd cilent, instead of moving the mouse with the finger / gamepad like now

**Comment by andrewtoups** [comment]
a workaround if you need function keys/super/alt/del/esc/etc: you can open the windows on-screen keyboard. not too much hassle if you add pin it to the start menu for easy access. could probably also add it as an app to geforce experience, but that might not be as useful.

**Comment by WSt89** [comment]
This thread is old but I've found a better workaround by installing a virtual keyboard for Android named hackers keyboard: https://github.com/klausw/hackerskeyboard

**Comment by 0x90shell** [comment]
> For anyone still hitting this: I built a host-side solution that works with any Moonlight client, including Android TV and Shield where there's no touchscreen to pull up a soft keyboard. Steam's keyboard can work but requires Steam running on the host, and the non-Steam Linux OSKs all need a mouse pointer or are dead projects.
>
> This is a standalone on-screen keyboard that takes direct gamepad input (D-pad/stick to navigate, face buttons for select/backspace/space). Second stick controls the mouse at the same time, and it has copy/paste.
>
> Runs on the Linux host so it works no matter which Moonlight client you're on: <https://github.com/0x90shell/gamepad-osk>
