### ISSUE TITLE
Moonlight blackscreen on fullscreen with emulators using Vulkan

### ISSUE THREAD

**Issue by piketrcechillas** [moonlight-stream/moonlight-android#797]
Hi all,
Currently I'm encountering a bug, when Moonlight connects to a PC running an emulator (e.g RPCS3) rendering using Vulkan, Moonlight won't display the game on fullscreen although audio is available (the game still run on PC). Window mode still works and also OpenGL works too. What might be the cause of this problem?
Looks like this is a global issue throughout multiple versions, since I encountered with all 3 moonlights for vita, android and browser

**Comment by irfanfadilah** [comment]
I can confirm this bug, I've tried Citra, Dolphin, Cemu and RPCS3 on my Vita and Android clients.

Every programs that using other than DirectX won't be able to stream in fullscreen mode, it will just displaying black screen; audio and input work normally.

Changing the render backend to DirectX in the emulator configuration will solve this, but the problem is only Dolphin that supports DirectX, most emulators only support OpenGL and Vulkan.

It will be difficult to ask emulator developers to add DirectX supports, so I think it will be best if the issue can be solved from Moonlight side.  Add supports for OpenGL or/and Vulkan.

**Comment by cgutman** [comment]
Unfortunately, this is something Nvidia will need to fix on their side. If GFE's capture code is not compatible with Vulkan, we can't do anything about that. We just only display the video we receive.

**Comment by irfanfadilah** [comment]
I see, so this is a bug from NVidia Game Experience.

I thought this is something that can be fixed from Moonlight side as the client.

Thanks for the explanation @cgutman. 👍

**Comment by lei8688** [comment]
This problem has been resolved, the latest beta driver has been updated, and the simulator has been tested to be normal. Test version driver address: https://developer.nvidia.com/vulkan-driver
