### ISSUE TITLE
Middle Mouse overriden by android command

### ISSUE THREAD

**Issue by lyndonguitar** [moonlight-stream/moonlight-android#822]
Android Device: Galaxy Tab S6 / Galaxy S9+
Keyboard: Galaxy Tab S6 Book Cover Keyboard
Mouse: Logitech B170 / M170 wireless w/ dongle connected (NOT bluetooth)

Mouse problem:
When pressing middle mouse, it issues android command for HOME instead of what is set in-game(for example in Rainbow Six - Activate Gadget, or in Dota 2, drag screen)

**Comment by cgutman** [comment]
This is an issue with Samsung's Android firmware. They are sending a home button press instead of a middle button press to apps. Other Android devices behave properly.

It's not possible for an app to override the home button, so we cannot work around the issue. It affects all apps on Samsung devices.
