### ISSUE TITLE
Virtual home button emulation

### ISSUE THREAD

**Issue by roob0** [moonlight-stream/moonlight-android#854]
I noticed that the 9.6.1 build has removed the feature to emulate and send the Home button with Start + Select and Start + RB on Android. The feature was super useful, considering that with Steam Chord config it's possible to send commands (such as Alt + F4, Alt + Enter, etc) but not every controller, like the Flydigi Wee 2, have an Home button. It was also useful on Firetv because the controller's Home button take you to the Firetv's home. Is it possible to send the Home button in other ways with the new build? It would be nice if the feature were added again and improved with the possibility to choose the button combo to emulate the Home key and to choose how long the Home button will be pressed (in the past builds  after having pressed and released Start and Select I had to quickly press the other keys, it would be nice if the home button could stay pressed for 1s or 2s).

**Comment by cgutman** [comment]
This did get reinstated a while back with https://github.com/moonlight-stream/moonlight-android/commit/b5f5e7307668bd92a62e3d5d733718d549e0faae and https://github.com/moonlight-stream/moonlight-android/commit/f0c625d85cec7746fd5fdc8572196b5d3a7a9a37

To reduce the change of interference with intentional combos in game (the original reason for removing them), the combos are only available on controllers that lack Select and/or Mode buttons.

The combos are:
- Start+Select or R1+Start = Home
- L1+Start = Select

**Comment by lyndonguitar** [comment]
> This did get reinstated a while back with [b5f5e73](https://github.com/moonlight-stream/moonlight-android/commit/b5f5e7307668bd92a62e3d5d733718d549e0faae) and [f0c625d](https://github.com/moonlight-stream/moonlight-android/commit/f0c625d85cec7746fd5fdc8572196b5d3a7a9a37)
> 
> To reduce the chance of interference with intentional combos in game (the original reason for removing them), the combos are only available on controllers that lack Select and/or Mode buttons.
> 
> The combos are:
> 
> * Start+Select or R1+Start = Home
> * L1+Start = Select
> 
> I just added them to the Setup Guide docs so they would be visible to other users.

Glad to hear this is reinstated, but another issue still exists. I hope you allow us to enable this option even with controllers that has Select and/or Mode buttons... Some controllers have hardcoded these to the Android 'back' button hence becoming unusable. For example, My Razer Kishi and Ipega controller has Home buttons that also work as Guide.. but they also function as Android back buttons with no way to unmap. 

When I press Home, the Steam Overlay opens, but I get kicked out of Moonlight too, so It is unusable. I hope the option is reinstated for these controllers too

**Comment by cgutman** [comment]
> Glad to hear this is reinstated, but another issue still exists. I hope you allow us to enable this option even with controllers that has Select and/or Mode buttons...

It's intended to only be disabled for controllers with _working_ Select/Mode buttons. If the button doesn't work, Moonlight can ignore it to allow the replacement combos to be used instead.

Are you using a Samsung device? According to some [Reddit posts](https://www.reddit.com/comments/ik210a), some broken OS updates completely hose `BUTTON_MODE` functionality. 

> Some controllers have hardcoded these to the Android 'back' button hence becoming unusable. For example, My Razer Kishi and Ipega controller has Home buttons that also work as Guide.. but they also function as Android back buttons with no way to unmap.

I assume you mean "home" not "back". From the [Kishi diagram](https://mysupport.razer.com/app/answers/detail/a_id/3146/~/at-a-glance%3A-razer-kishi), it appears there are 3 buttons. 2 of them are normal function buttons (Start and Select, I assume).

The 3rd is a "special function button" as they call it. The [Kishi FAQ](https://mysupport.razer.com/app/answers/detail/a_id/3562/) implies that the special function button can be customized by applications somehow. They don't elaborate on how and their developer portal says nothing about this. You could try an app like [this](https://play.google.com/store/apps/details?id=ru.elron.gamepadtester&hl=en_US&gl=US) and see if the special function button still acts like the home button.

Is your Kishi Android controller the Xbox variant or non-Xbox variant? That might make a difference in the mapping of the special function button.

**Comment by lyndonguitar** [comment]
> It's intended to only be disabled for controllers with _working_ Select/Mode buttons. If the button doesn't work, Moonlight can ignore it to allow the replacement combos to be used instead.
How can I force moonlight to ignore it to allow the replacement combos? is there an option?

> Are you using a Samsung device? According to some [Reddit posts](https://www.reddit.com/comments/ik210a), some broken OS updates completely hose `BUTTON_MODE` functionality.
I am using a Samsung S9+ and Samsung Galaxy Tab S6

> I assume you mean "home" not "back". From the [Kishi diagram](https://mysupport.razer.com/app/answers/detail/a_id/3146/~/at-a-glance%3A-razer-kishi), it appears there are 3 buttons. 2 of them are normal function buttons (Start and Select, I assume).
Yes, I meant the "Home" button, my bad. The Kishi's Home button is hardcoded to 'Android Home command', but when using gamepad tester, Kishi's Home button still outputs a "Guide/Button" (It still opens Steam Overlay/Big Picture), but at the same time, It also outputs the 'Android Home command', minimizing everything and returning me to Home as soon as I press it.

So If I'm playing a game on Steam, I press the Kishi Home, My phone goes back to home menu. I open moonlight again and return to Steam overlay already opened. I have no way of unbinding or remapping the "android home command"

Sorry If my explanation is making it more confusing.

> Is your Kishi Android controller the Xbox variant or non-Xbox variant? That might make a difference in the mapping of the special function button?
I have a non-Xbox variant. I also have iPega-9083, iPega-9087,iPega-9021 and the "Home" button is definitely unusable on all controllers. As you said, Maybe due to my devices being Samsung. I just hope I can have the alternative of pressing Select+Start instead, to avoid the faulty Home Button implementation of my devices
