### ISSUE TITLE
Home/Xbox/PS button alternative?

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-android#887]
For those of us who don't have an Xbox/PS/Home button on our controller/s, how can we trigger a press of this button for overlay/chording purposes?

Can we send an input keyevent adb command? If so, which identifier does Moonlight assign to Home/Xbox/PS button?
Can we somehow customise the controller overlay to show only a home button in the corner?

Thank you.

**Comment by PhantomLiberty** [comment]
I swear there used to be a hotkey for this but as of late it doesn't seem to do anything. Pretty sure it was double tap start while holding select. Makes it incredibly annoying to configure Steam's controller profiles exclusively from the remote device.

The workaround I've had to use is to setup a multi-key bind for my keyboard overlay keys. Works great for the overlay but it doesn't help with chord functionality whatsoever.

**Comment by roob0** [comment]
A basic home button emulation was already present before 9.6.1 version, by pressing Select + Start or Select + RB. After pressing the combo, it was also possible, in a short time, to press other buttons and send commands as configured in Steam's Chord config. I decided to stick with 9.5.1 version for this reason.

**Comment by WreckWren** [comment]
> A basic home button emulation was already present before 9.6.1 version, by pressing Select + Start or Select + RB. After pressing the combo, it was also possible, in a short time, to press other buttons and send commands as configured in Steam's Chord config. I decided to stick with 9.5.1 version for this reason.

Thank you @roob0 I will roll back.

**Comment by cgutman** [comment]
The reason I removed it was because:
- It was not very discoverable (not many people used it)
- It could collide with existing game combos (I got complaints that people couldn't press LB/RB + Start in their games)
- These combos were originally for emulating Select on Ouya gamepads that didn't have that button. Emulating Guide was just an afterthought. Now most people just use Xbox or PS4 controllers that already have all 3 of those buttons and Ouya is long gone.
- It was specific to Android (other Moonlight clients never supported it)

I don't think I'm going to write a configuration dialog, because I have other plans to expose the guide button in a more user friendly way. However, I can bring the Start+Select combo back if you think that would meet your needs. What do you think?

**Comment by WreckWren** [comment]
> The reason I removed it was because:
> 
> * It was not very discoverable (not many people used it)
> * It could collide with existing game combos (I got complaints that people couldn't press LB/RB + Start in their games)
> * These combos were originally for emulating Select on Ouya gamepads that didn't have that button. Emulating Guide was just an afterthought. Now most people just use Xbox or PS4 controllers that already have all 3 of those buttons and Ouya is long gone.
> * It was specific to Android (other Moonlight clients never supported it)
> 
> I don't think I'm going to write a configuration dialog, because I have other plans to expose the guide button in a more user friendly way. However, I can bring the Start+Select combo back if you think that would meet your needs. What do you think?

Hi @cgutman & thanks for your detailed reply.

It would be very helpful to re-enable that one yes, however it sounds like you are moving ahead to a custom binding for the home button in the future? Especially with an option of on-screen/touch (moveable) for that button that sounds like the most elegant solution. One could easily just sit a touch button in the dead space on the sides with 18+:9 phones.

Would it be possible to make the binding include the bumpers again if implementing the start+select binding? Many desktop controller apps use start+select for hot keys (such as controller companion). 

Thank you again for your reply.

**Comment by cgutman** [comment]
The on-screen button is where I'm moving towards with a single button combo to summon that on-screen overlay. For now, I restored the button emulation in v9.7.5 but now it is only enabled for buttons that are not physically present. That should hopefully reduce the blast radius of these interfering key combinations.

I stuck with Start+Select for Guide rather than RB+Start (for gamepads with a Select button) because the complaints I received about the button emulation combo were centered around the ones involving the bumpers. But as I mentioned, this is all going to be redone anyway.

**Comment by roob0** [comment]
Happy that the home emulation was added again. Thank you.

**Comment by gricardo93** [comment]
I'm using version 9.7.7 but the combo start + select does not work as the home button. Do I just need to press them at the same time?

A on-screen button would be perfect.

**Comment by WreckWren** [comment]
> 
> 
> I'm using version 9.7.7 but the combo start + select does not work as the home button. Do I just need to press them at the same time?
> 
> A on-screen button would be perfect.

Yeah, on-screen would avoid compatibility issues with apps like Controller Companion.

**Comment by ReenigneArcher** [comment]
It would be beneficial for those of using Nvidia Shield as they refuse to give up control of the guide button, even as an option. (https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/297338/xbox-one-s-guide-button-issue/2158351/)

Giving the user the option like RetroArch does would be nice.

![image](https://user-images.githubusercontent.com/42013603/106341029-bef8da00-6269-11eb-8785-98eb98a9526f.png)

Side question... Is the new Xbox Series S/X controllers share button detectable by moonlight?

**Comment by cgutman** [comment]
> It would be beneficial for those of using Nvidia Shield as they refuse to give up control of the guide button, even as an option.

You can use Start+Select on Shield controllers. 

> Side question... Is the new Xbox Series S/X controllers share button detectable by moonlight?

It depends on if the OS driver exposes it.
