### ISSUE TITLE
The mouse is misplaced during text editing

### ISSUE THREAD

**Issue by WACrown** [moonlight-stream/moonlight-android#896]
![IMG_20201117_105819](https://user-images.githubusercontent.com/48990489/99341056-1ec72200-28c4-11eb-916a-f95cb0fdc4d4.jpg)

**Comment by Swimtoto** [comment]
Hi,
I have the same isssue only since the last version of Moonlight 3.0.0.
The cursor was perfectly place with version 2.2.0.

I tried to set different configuration in the settings but nothing changed. The "misplacement" is still there. Very annoying when you do photo editing for exemple where you need precision.

**Comment by cgutman** [comment]
This is caused by an interaction between Windows 10 2004/20H1 and Nvidia 450+ drivers. They are overlaying the cursor onto the video stream at the wrong location. This is something Nvidia will need to fix an a GeForce Experience or Nvidia driver update.

The cursor is encoded into the video stream by GeForce Experience on the host (not drawn by Moonlight on top of the video), so there is nothing Moonlight can do to solve this.
