### ISSUE TITLE
How are Resolution differences handled within Moonlight?

### ISSUE THREAD

**Issue by Skyyblaze** [moonlight-stream/moonlight-android#903]
My PCs primary screen is 1080p and the phone I'm currently using with Moonlight is just 720p however I don't want to set Moonlight on Android to 720p because that changes the desktop resolution whenever I stream a game which in turn messes with the size and position of most windows and programs I often have open on my PC.

Now to my question, if I set Moonlight to 1080p but my phone is just capable of 720p will the image be downsampled on the client or host?

Ideally I would like for the image to be downsampled on the PC to 720p and then streamed over to the phone to save network bandwidth. Does Moonlight already do this and if not, would such a feature be possible?

Something like:

"Downsample to Client Resolution on Host"

**Comment by cgutman** [comment]
If you set Moonlight to 1080p, the video stream from your PC will be 1080p and it will be downsampled on your client.

Moonlight doesn't provide an option to independently select desktop resolution from stream resolution (I'm worried that might be confusing to users, and wouldn't be very powerful anyway because the only supported desktop resolutions are 720p, 1080p, and 4K). However, if you just want GeForce Experience to not mess with your desktop resolution, you can [stream your desktop](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop) which won't mess with the resolution.
