### ISSUE TITLE
Allow user to disable android imput

### ISSUE THREAD

**Issue by AlfonsCasanova** [moonlight-stream/moonlight-android#91]
You can't play with controller connected directly to PC, because after connecting android device game changes controller to keyboard.

**Comment by halfluck** [comment]
Hey AlfonsCasanova,

i'm not sure this can be handled by Moonlight as Gamestream is doing this.

Have you tried the below? I just tried it myself and it works great only issue I cant resolve is you don't get any sound on the TV, but it plays thru the PC instead?


Using a wired/wireless controller connected to the GFE PC instead of the streaming device
 Normally, Moonlight sends controller input from the streaming client which gets sent to the game by GFE. If you want to connect a controller to your PC instead of the streaming device, GFE can cause some problems because the emulated controller still appears to games as controller 1. Luckily there is a workaround for this. You'll need to rename the DLL that Nvidia is using to send controller input so it won't be used anymore. On 32-bit and 64-bit Windows, rename rxinput.dll to rxinput.dll.old on in C:\Program Files\NVIDIA Corporation\NvStreamSrv. On 64-bit versions, there's another copy of the DLL in C:\Program Files (x86)\NVIDIA Corporation\NvStreamSrv which you'll want to rename. You may have to do the renaming again if GFE does an update, but it should allow you to use your controller normally on games that only support 1 controller.

Source ==> http://forum.xda-developers.com/showthread.php?t=2505510

Cheers Rob.

**Comment by AlfonsCasanova** [comment]
Thanks for solving my issue!
I must say it's not easy way, but works perfectly.
You saved me few dollars that I was about to spend on OTG cable.
This should be visable somewhere for other people!
Thanks again.

**Comment by halfluck** [comment]
Ahh Awesome News! great to hear.
