### ISSUE TITLE
Beware using Native phone res

### ISSUE THREAD

**Issue by PhantomLiberty** [moonlight-stream/moonlight-android#910]
Every time I try to switch to the phone resolution on a game my video drivers meltdown and have to be cleaned with DDU in safe mode. Gets me stuck in a boot loop.

**Comment by cgutman** [comment]
What resolution, Nvidia driver version, host GPU, and Windows version?

**Comment by PhantomLiberty** [comment]
Latest Windows 10 & drivers. 2080 ti. 2340 x 1080 (ROG Phone 2)

**Comment by cgutman** [comment]
I need exact versions, please. Due to compatibility holds, "Latest Windows 10" could be anything from 1909 to 20H2. Drivers versions too, since somebody looking at this issue months later is not going to have a clue which driver was current at time.

What monitor is connected? I've done 3040x1440 (Pixel 4 native res) on an HDMI fake monitor dongle with no problems on Win10 20H2 and 460.89 drivers.

**Comment by PhantomLiberty** [comment]
I see.

Windows:  20H2 - 19042.685

Nvidia:  460.89

Monitor:  ASUS PG279Q

**Comment by cgutman** [comment]
I was able to reproduce the bug here with 19042.685 and 460.89 drivers. Some about that resolution in particular is triggering a GPU driver bug. Others similar resolutions don't crash. We should probably report that to Nvidia to get fixed in a new driver update.

In any case, I've updated the wording in the native resolution warning to be more clear about the possible issues that can result from custom resolutions.
