### ISSUE TITLE
H.265 doesn't work on my phone 

### ISSUE THREAD

**Issue by Dean1999** [moonlight-stream/moonlight-android#916]
I use my laptop as service PC graphics card is GTX1650, people told me IT support HEVC, and i use my phone as client which is blackshark3 pro, the chip is snapdragon 865. I found a HEVC decoder in my phone but I don't know why it just won't work. Here is the screenshot, can anyone tell me how to make H.265 work on my phone? Much appreciate.
![Screenshot_2021-01-09-23-31-58-643_com limelight](https://user-images.githubusercontent.com/77203898/104103346-87d38080-52dc-11eb-8063-beacd9a54708.jpg)
![IMG_20210110_003445](https://user-images.githubusercontent.com/77203898/104103347-8d30cb00-52dc-11eb-8db0-2a18dceb69d5.jpg)

**Comment by cgutman** [comment]
The problem is that the GTX 1650 is incorrectly hardcoded in GeForce Experience to have no HEVC support. This is a bug on Nvidia's side, similar to https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-doesnt-hevc-or-hdr-streaming-work-on-my-rtx-3000-series-gpu though I don't know if Nvidia's hotfix works for this case or just RTX 3000 GPUs.

**Comment by Dean1999** [comment]
> The problem is that the GTX 1650 is incorrectly hardcoded in GeForce Experience to have no HEVC support. This is a bug on Nvidia's side, similar to https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-doesnt-hevc-or-hdr-streaming-work-on-my-rtx-3000-series-gpu though I don't know if Nvidia's hotfix works for this case or just RTX 3000 GPUs.

In this case, there nothing we can do about it, thanks you for you answer😊
