### ISSUE TITLE
Error -5 Failed to start video stream establishment

### ISSUE THREAD

**Issue by pfroo40** [moonlight-stream/moonlight-android#918]
I am on a Samsung Tab A7 with Android 10, using the latest Store version of Moonlight, and the latest nVidia GeForce Experience software on my host PC. I get this error when establishing a connection, it handshakes and then fails. It was working fine about a week ago. Moonlight still works fine on my phone, running the same version. My settings are unchanged from the last time it worked. I can't find reference to this error.

Thanks!

**Comment by cgutman** [comment]
That error indicates that the decoder wasn’t able to configure itself with the video stream config data.

What resolution is Moonlight set to stream?

**Comment by lacrimstein** [comment]
I'm running into the same issue with a Kindle Fire HD 10. This only happens when configured to use native resolution (which is 1920x1200 on that tablet). My host monitor is 2560x1440, and I can change resolution to 1920x1200 from the desktop settings just fine. I can work around the issue by configuring Moonlight video resolution to 1080p, but it would be nice to be able to stream at native resolution, without black bars.

**Comment by cgutman** [comment]
Error -5 means your hardware decoder isn’t compatible with the resolution, so I don’t think 1920x1200 will work on that device.

That error should be more clear, but the warning dialog you got when you selected the native resolution did mention the possibility that it just won’t work on your device. Unfortunately that appears to be the case here
