### ISSUE TITLE
Wake on lan and controller remapping

### ISSUE THREAD

**Issue by HighPingTek** [moonlight-stream/moonlight-android#921]
Is it possible to implement these two features?

**Comment by cgutman** [comment]
Wake on LAN has been supported in Moonlight for years, so not sure what you’re asking for.

Controller remapping is not really a feature that I would like to spend engineering effort on. Moonlight follows the Android gamepad standards, so any gamepads designed for Android should work perfectly with no remapping required if they follow the standard. Likewise Android itself  contains mappings for many common controllers like Xbox and PS. For gamepads that do require custom mappings, Moonlight should have them built-in so users don’t have to manually set them themselves. In some software, gamepad mapping support ends up being a crutch that enables shipping really poor quality default mappings because the users just fix it themselves.

**Comment by HighPingTek** [comment]
sorry i never noticed that wake on lan was already there

as far as the remapping is concerned, I mean the possibility of putting the triangle button in the square one or creating macros, similar to what you can do with DS4WINDOWS for dualshock 4
