### ISSUE TITLE
Games in GFE not showing up in Moonlight

### ISSUE THREAD

**Issue by derrickb** [moonlight-stream/moonlight-android#940]
In the GeForce Experience app under Home, I see 27 titles.

However in Moonlight on Chromecast, I only see 13, not including the Steam launcher.

Not all the missing games are from the same platform/store. For example on Moonlight I see a mix of Steam games, GOG, and others. An example of a game I see in both GFE and Moonlight is the original Half-Life (Steam), but a game missing from Moonlight is Cyberpunk 2077 (GOG).

Adding games manually to Gamestream does get them to show up in Moonlight. This worked for CP2077, for example.

**Comment by cgutman** [comment]
This is normal behavior of GeForce Experience. See our FAQ entry - https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-doesnt-moonlight-show-all-of-my-games

CP2077 for sure is not GameStream-certified by Nvidia, so that's why it won't show up by default in the GameStream list (despite the fact that it is supported for optimal playable settings functionality in GFE). They are pretty much not certifying many games for GameStream anymore (with the exception of Borderlands 3 recently).

You'll need to add the game executables using the SHIELD tab of GFE to get them to appear in Moonlight and the Shield GameStream client.
