### ISSUE TITLE
Number of controllers seems limited to 4 due to Xinput

### ISSUE THREAD

**Issue by mehditlili** [moonlight-stream/moonlight-android#941]
I am using moonlight on a 2020 Amazon firestick 4k. I use Dualshock 4 controllers connected via Bluetooth to my firestick. I can easily pair and connect all my 5 controllers. However, when I use Moonlight to connect to my Windows machine, only 4 appear. I double-checked using Rewasd and it only shows 4 Xinput controllers, which the max number Xinput supports.
Is it possible to switch to using DirectInput instead of Xinput?

**Comment by cgutman** [comment]
It's not a matter of DirectInput vs XInput directly (that's a Windows-ism, and not relevant to Moonlight on Android). Moonlight can detect more than 4 controllers, but the problem is that Nvidia's host-side software will not enumerate more than 4. I just tested locally with a custom build that reports 5 controllers to the host and still only see 4 get created by the host.

There's no technical reason why the 4 controller limit exists that I can think of. I know Nvidia used to use XInput DLL hooking to emulate controllers in older versions of GeForce Experience (which is limited to 4 controllers), but now they expose virtual USB devices which obviously have no such 4 device limit. I suspect the limit simply remains due to the vestiges of the old XInput hooking code, and that nobody really complained to them about it.
