### ISSUE TITLE
The isGame flag is causing problems activating HDR in sony TVS

### ISSUE THREAD

**Issue by diogosena** [moonlight-stream/moonlight-android#945]
Sony tvs can't activate HDR in "isgame" mode.

Quoting another user @geneccx on the issue #490

"I believe HDMI inputs cause the TV to go into a different game mode. When you open a native Android game, the picture menu is labeled as Apps (game), which is what removes the HDR setting and auto detection. "

Related:

https://github.com/moonlight-stream/moonlight-android/issues/490#issuecomment-351559327

**Comment by cgutman** [comment]
Yeah, this is a problem I'm aware of, but there's not really a way to fix it.

If we unset the `isGame=true` flag, some Android TVs will not kick into game mode and latency will be awful (which is the reason we added it in the first place). Since `isGame` is static signed metadata that's included in AndroidManifest.xml, it cannot be modified at runtime based on whether you want to stream HDR or not or enabled/disabled based on the model of Android TV you have. Since Moonlight is a highly latency-sensitive application, I think `isGame=true` is the right compromise.

Google actually realized this problem and [introduced a function in Android 11](https://developer.android.com/about/versions/11/features#low_latency) to control this behavior. Not only can the application control whether ALLM is used with the Android 11 API, the user can also opt-out of ALLM themselves (which is what you want to do). Unfortunately, you're still at the mercy of your TV actually getting updated to Android 11 for any of this to work.

**Comment by diogosena** [comment]
Thanks for your reply, i ended up making a custom version without this flag and its working great.
Maybe you can add a "sony_hdr" apk to releases page, besides root and non root apks.

**Comment by Josh015** [comment]
Oh my god this one was driving me nuts and now I find out it's a Sony-specific problem! @diogosena how did you make that custom app and how do you load it onto the TV? 🥺

**Comment by diogosena** [comment]
I used some app named "apk editor pro" to edit the moonlight apk.
Hit me up at gmail, same username, and I can send you that custom version.

**Comment by Josh015** [comment]
Using the patched version from @diogosena it appears to work on my fully up to date a9g. It defaulted to the "Custom" picture mode, but I was able to manually switch it to "Game" mode without too much trouble and it said it was in HDR mode from there.

**Comment by Josh015** [comment]
Okay, I tried the patched version provided by @diogosena and I got it to work exactly once. Unfortunately, subsequent sessions failed to switch over to HDR mode. Sadly @cgutman appears to be correct in that nothing more can be done about this until Sony updates their TVs. 😒

**Comment by Josh015** [comment]
Okay, so I did some more testing and found a way to make HDR work reliably on my Sony TV.

**Prerequisites**
- HDR monitor and compatible GPU on my computer.
- HDR-capable Sony Android TV.
- Patched Moonlight launcher from @diogosena installed on the TV.
- Windows configured to run in HDR mode.
- [Moonlight HDR launcher](https://github.com/lyckantropen/moonlight_hdr_launcher) installed on my PC and configured to launch Steam Big Picture in HDR mode and clean up on close.
- Moonlight app configured for HDR. It also needs to be manually set to "Game" mode, since the patch prevent it from defaulting to that.

**Steps**
1. Launch Moonlight on the TV like normal.
2. Launch the "Mass Effect: Andromeda" link to trigger Moonlight HDR Launcher.
3. Launch any Steam game you want to run in HDR mode.
4. <Have Fun>
5. Close out the game.
6. Exit Steam (not minimize or exit Big Picture). This appears to be necessary to get the HDR launcher to exit properly and be able to launch again on subsequent attempts.
7. Use remote to go back to Moonlight menu and manually close the session.

If anyone would like to reproduce these steps and confirm it works for them then we can hopefully distribute the information.

**Comment by Kev506** [comment]
I don't think isGame flag is the problem, I maybe wrong but here's my senario, Sony Bravia KD-43XH8505 Android 9, running moonlight connected to my gaming laptop. The laptop has an EDID Emulator, which I used to clone the settings from the TV, all HDR settings on Windows are enabled. When running moonlight with HDR experimental enabled the TV picture setup shows picture mode as game, if I select a game, I'll use 3 games as examples:

COD WW2 (Steam) launches perfectly in HDR confirmed in the TV picture setup.
GR Breakpoint, (Ubisoft) "NOT HDR10" according to moonlight, but launches perfectly in HDR confirmed in the TV picture setup.
F1 2020, (Steam) "NOT HDR10" according to moonlight, HDR enabled in game, launches and is running in HDR but the TV picture setup does not confirm HDR?.

Is it possible this is caused by Nvidia Gamestream and not moonlight, although moonlight seems not to detect all games that are HDR compatible.

Still love the app though, even with this issue.

**Comment by Kev506** [comment]
Solved issue on Sony Bravia not detecting HDR signal: it seems to be the games config files, I checked F1 2020, F1 2019, Grid Ultimate, all config files had the HDR mode set to 2, changing to HDR mode 1 immediately solved the issue and the TV correctly identified the HDR signal. So isGame flag is not the issue, it's the games outputting the wrong HDR mode for the specified output TV or monitor. 

Hope this is of help.

**Comment by diogosena** [comment]
@Kev506  the isgame flag definitely solved my issues, but I'm gonna take a look at your workaround.. where are those game config files you mentioned?

**Comment by Kev506** [comment]
@diogosena They are located user\documents\mygames, game folders should be in there with their config files, they're in XML format.

I have also solved the issue with F1 2020 after changing the config file it crashed, however I noticed the game is using DX12, so I added a command to the game properties in steam to force it to use DX11. Now that is also detected as an HDR format on the TV.

I have seen various post around concerning DX12 having issues with HDR, hopefully Microsoft will fix it.

**Comment by diogosena** [comment]
Those are game related files, not gamestream, that's an entirely diferent problem.

To check if you have the isgame problem, just launch a hdr game using a phone (with hdr support obviously) and test the same game on the sony tv, if the hdr worked on phone and didnt worked on the sony tv, then you have the isgame problem.

**Comment by Kev506** [comment]
@diogosena  GR Breakpoint is Gamestream and launches fine on the TV without any problems. When running I check the picture settings on TV and it is marked isGame with the HDR logo also showing.

All games I'm using are through Gamestream, all HDR capable are now streaming to the TV in HDR even though they are marked isGame.

**Comment by SirFailaL0t** [comment]
Setting the isGame flag to false and then manually switching my TV to game mode, for reduced lag, also fixed HDR for me.
If anyone wants to replicate this for their Sony Android TV here is how I did it:

To change the setting in the AndroidManifest.xml, the java tool ManifestEditor can be used.
https://github.com/WindySha/ManifestEditor

Then I downloaded the Moonlight APK and put it into the same folder.
Then I opened a terminal/cmd window in that folder and ran the command:
`java -jar .\ManifestEditor-1.0.2.jar .\app-nonRoot-release.apk -aa android-isGame:false -s`
(a java installation is required for this)

This spits out a self signed apk of Moonlight, with isGame disabled, which can then be installed on the TV.
