### ISSUE TITLE
Fire stick tv 4k

### ISSUE THREAD

**Issue by joitronix** [moonlight-stream/moonlight-android#964]
The games load but only see a screenshot and no more image, the sound works good.

The firestick have the last update.

**Comment by seanocali** [comment]
The latest Geforce Experience requires the latest version of Moonlight and it's not on the Amazon store you. You'll have to install the apk manually or wait (a few days?).

**Comment by joitronix** [comment]
> The latest Geforce Experience requires the latest version of Moonlight and it's not on the Amazon store you. You'll have to install the apk manually or wait (a few days?).

Updated with the last apk from git hub and updated gforce experience to the last too and keep black, in my smartphone work perfect.

**Comment by reloxx13** [comment]
> 
> 
> > The latest Geforce Experience requires the latest version of Moonlight and it's not on the Amazon store you. You'll have to install the apk manually or wait (a few days?).
> 
> Updated with the last apk from git hub and updated gforce experience to the last too and keep black, in my smartphone work perfect.

works fine with latest version. i had 9.8.2 and latest is 9.8.6 (nonroot). amazon is really slow in rolling out.   
download von [github releases](https://github.com/moonlight-stream/moonlight-android/releases/latest) and install manually with [wireless file manager](https://www.amazon.com/Wireless-Manager-Transfer-Files-Explorer/dp/B07MMTTWF3) app found in amazon store.

**Comment by Anthuzad** [comment]
I'm having the same problem with an FireTV Cube. I've got the newest version of Moonlight installed, but the rendered FPS on the client stays at 0 after connecting.

**Comment by cgutman** [comment]
The Amlogic decoder doesn’t like the HEVC keyframes sent by recent GFE and drivers. I believe Moonlight should default to HEVC off for this broken hardware.

Did you enable HEVC manually or is this happening even with HEVC in the default auto state?

**Comment by Anthuzad** [comment]
I wanted to test the different combinations for you and reinstalled Moonlight for that purpose - out of nowhere everything started working again... H.264 as well as H.265 seem to be working just fine now.

I have no explanation why Moonlight stopped working out of the blue and now started working again. I'm positive the reinstall is not connected to it because I reinstalled it a number of times in the hopes of getting it to work, this is very strange.

However, I'm happy that it is working again. If you'd like me to do anything to test or isolate possible problems let me know!
