### ISSUE TITLE
Moonlight not finding Gamestream ready PC

### ISSUE THREAD

**Issue by MichaelRupertDev** [moonlight-stream/moonlight-android#97]
My Nexus 6 running Moonlight is unable to find my Windows 10 GTX 970 PC on the network. Adding with IP also does not work. I have opened the ports in my PCs firewall, as well as forwarded the ports on the router. 

Any ideas?

**Comment by GazaIan** [comment]
I was having the same issue. Unfortunately, the only solution I can suggest to you is to reinstall the Moonlight app and try again later. When I first tried it, my PC showed up, but I couldn't connect. Then the next morning my PC showed up and I was able to connect and stream with no issue. Not sure what the issue was, it just solved itself.

**Comment by cgutman** [comment]
Closing this issue since it's so old. Reopen if it affects modern versions of GFE and Moonlight.
